### ISSUE TITLE
Without config.rb file, unpredictable location of stylesheet.

### ISSUE THREAD

**Issue by coopersita** [oklai/koala#107]
I'm using Koala 1.4.3 on a Mac running 10.8.5. 

If I have no config.rb file, and no 'css' or 'stylesheets' directory, on first manual compile, Koala creates a 'css' empty folder, and a 'stylesheets' folder with the css file in it.

I had other people try it, and some had the opposite issue, where 'stylesheets' was empty, and 'css' had the stylesheet.  I'm not sure which version they had, though (could have been the beta).

In any case, two folders are created, and the stylesheet is in one of them.

I have not seen the issue when you have a config.rb file specifying output directories.

Thanks

**Comment by henrix343** [comment]
it's still pain in the ass - same here.
