### ISSUE TITLE
Autoprefixer support

### ISSUE THREAD

**Issue by sheabunge** [oklai/koala#108]
[Autoprefixer](https://github.com/ai/autoprefixer) is a great tool that automatically adds prefixes to your CSS depending if [Can I Use](http://caniuse.com/) says that they're needed. It would be great if Koala supported running Autoprefixer on compiled Less/Sass/Compass code.

**Comment by fredydeltoro** [comment]
hey hello there is some trouble with -moz- prefix don't add
