### ISSUE TITLE
watch deep imports.

### ISSUE THREAD

**Issue by istrasoft** [oklai/koala#137]
Some SASS files in my projects seem not to be watched and do not trigger a recompile...

Here is the folder tree:

```
/app.scss
/_myproject.scss
/myproject/_mycomponent.scss
```

In `/app.scss` I have :

```
@charset "UTF-8";
@import "myproject";
```

in `/_myproject.scss` I have :

```
@import
  "foundation",
  "myproject/mycomponent";
```

When I edit the contents of `/myproject/_mycomponent.scss`, the recompile is NOT triggered, even though if I manually hit the Compile button, everything is fine.

Actually, looking at the "imports" contents in the .koala/projects.js file in my home folder, it appears that all koala ever watches is the first-level imports, and does not recurse. Is that so ? Will this be extended to watch imports in imported files too please ?

**Comment by julmot** [comment]
Seems still not working

**Comment by clemorphy** [comment]
I really need the autocompile feature to work when changes happen in @imported sass files.
Still not working with V 2.0.4
Any date for this feature ?

**Comment by clemorphy** [comment]
Well, on an other project, a change in an imported sass does not trigger the compilation, even with the full file name like mentioned above. I can't find what is wrong ...

**Comment by erythro** [comment]
@oklai, @clemorphy is right, in sass the full file name is needed for the autocompile to work, so even though something like

`@import base`

is valid Sass for importing a file called "_base.sass", it's not being watched by Koala, and yet 

`@import "_base.sass"`

works perfectly.  If this isn't a bug, can it at least go into the docs as I straight up didn't realise Koala could autocompile imports and @clemorphy's solution has dramatically improved the usability of Koala for me!

**Comment by julmot** [comment]
@clemorphy Dafuq, how old are you?

**Comment by itsmrwalsh** [comment]
If anyone is still struggling with this in 2019 - I can confirm that each partial will need its own line. 
e.g. 
`@import "scss/file1.scss","scss/file2.scss"; `
^^ will not auto-compile on changes to those files

```
@import "scss/file1.scss";
@import "scss/file2.scss";
```
^^ This will auto-compile if you change either file.
