### ISSUE TITLE
Error when compiling .scss file

### ISSUE THREAD

**Issue by denismarian** [oklai/koala#162]
I have an error when compiling .scss file, appears notification that is error and path to my .scss file. With .less files is ok. I downloaded Koala about one week ago and it always shows me this error.

Windows 7 64, have ruby installed.

**Comment by buzznick** [comment]
I was having the same issue and sebchauss solution worked for me. Cheers.

"I set the value to 10000 and it worked (file "%koala%\app\scripts\compilers\SassCompiler.js" line 149)"

**Comment by Mervel** [comment]
I have the same problem and
"I set the value to 10000 and it worked (file "%koala%\app\scripts\compilers\SassCompiler.js" line 149)"
doesn't work for me. Do you have any other ideas?

**Comment by FreezyExp** [comment]
50000 worked for me on an cheap laptop, it just takes too long

**Comment by mort3za** [comment]
Updating ruby to 2.2.1 and setting timeout to 10000 (based on @TillMatthis comment) solved my issue.

platform: win 8.1 x64

**Comment by eric-harms** [comment]
Thanks to everyone who discovered a fix. I was pulling my hair out. 10000 worked for me.

**Comment by oklai** [comment]
Thanks all, I will set the default value of maxBuffer to  `10000*1024`.

**Comment by Judder** [comment]
Setting timeout to more than 5 seconds as per above fixed this nicely

You can test if this is the problem by removing a number of your include files, to make the compilation less than 5 seconds, and then it will compile Error free again

**Comment by soumen-sarkar** [comment]
I have the same problem and
"I set the value to 10000 and it worked (file "%koala%\app\scripts\compilers\SassCompiler.js" line 149)"
doesn't work for me. Do you have any other ideas?
![screenshot 2015-10-12 15 47 18](https://cloud.githubusercontent.com/assets/14568229/10425850/9e308876-70f8-11e5-963c-a60e2f33c705.png)

**Comment by ucavus** [comment]
To @soumen-sarkar and others still getting this error, *go higher*. I tried `30000` and still had errors. Setting `60000` (one minute) solved it for me.

**Comment by alenb** [comment]
I had the same blank error message with just the path. My solution was to untick `Source Map` and it worked for me. Not sure if this will help, but I thought I'd leave it here anyways.

**Comment by Cf-251** [comment]
changing to 15000 worked)

**Comment by donomron** [comment]
@sebchauss trick worked for me too! Thanks

**Comment by bertanyaman** [comment]
@TillMatthis 10000 is also worked for me !

**Comment by peterromero** [comment]
I changed timeout to 500000 and maxBuffer to 100000*1024, and am still getting the error. I also unticked Source Map. I added the lines to the SassCompiler.js and also to package.json but I don't get anything in the console... just a blank error. What else can I try?

**Comment by opanasenkomaksim** [comment]
This error occurred after reinstalling from disk C to disk D in my case. I returned it to drive C, and it works for me
