### ISSUE TITLE
sass里有中文注释编译报错

### ISSUE THREAD

**Issue by doyoe** [oklai/koala#193]
sass文件里有中文注释时编译报错，是有设置么？

**Comment by zhwangart** [comment]
这是什么意思？

/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'sass' (>= 0) among 15 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/ZhihanWang/.gem/ruby/2.3.0:/Library/Ruby/Gems/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /Applications/Koala.app/Contents/Resources/app.nw/bin/sass:17:in `
