### ISSUE TITLE
@import compass

### ISSUE THREAD

**Issue by luisalves73** [oklai/koala#199]
In order for Koala to compile my sass file without errors, I had to include compass css into my sass file with

@import "compass/css3";
@import "compass/utilities";
@import "compass/typography";

Is this normal?

Thanks

**Comment by larryleeelucidsolutions** [comment]
I'm having the same problem. Has anyone resolved this?

**Comment by larryleeelucidsolutions** [comment]
I believe that I solved the problem. When selecting a file to compile using Koala, be sure to check the "Compass Mode" check box in the settings menu presented on the right.

**Comment by luisalves73** [comment]
Ok, thanks!
