### ISSUE TITLE
It can not be launch in ubuntu 14.04 64bits

### ISSUE THREAD

**Issue by bstr2w** [oklai/koala#246]
error:

/usr/share/koala/koala: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory

It requires a shared library libudev.so.0 that does not exist in this version of ubuntu. It can be fixed by adding a symbol link 'libudev.so.0' to 'libudev.so.1'.

**Comment by pfernandez** [comment]
Thanks oklai, you solution worked for me, although I first found it at [askubuntu](http://askubuntu.com/questions/288821/how-do-i-resolve-a-cannot-open-shared-object-file-libudev-so-0-error).

**Comment by arvi** [comment]
Thanks https://github.com/oklai/koala/wiki/Unable-to-run-Koala-in-Linux worked for me :smile:

**Comment by PenAndPapers** [comment]
followed the instructions @ https://github.com/oklai/koala/wiki/Unable-to-run-Koala-in-Linux which fixed the issue. Thanks! :)
