### ISSUE TITLE
[Ubuntu 13.04] run error with libudev0

### ISSUE THREAD

**Issue by lazo99** [oklai/koala#26]
after installing the Ubuntu 64-bit .DEB I had to create a sym link for Koala to run.

First I have to change directories:
<code>cd /lib/x86_64-linux-gnu/</code>

Then use create the following sym link
<code>sudo ln -s libudev.so.1 libudev.so.0</code>

**Comment by Mezzle** [comment]
Can this not be compiled against the correct libudev?

**Comment by rysiavets** [comment]
ништяк, все работает.
