### ISSUE TITLE
Error on start - Cannot read property 'appVersion' of null

### ISSUE THREAD

**Issue by robeno** [oklai/koala#293]
Hi,
when I start Koala, error appear:  
![error](https://cloud.githubusercontent.com/assets/4101314/4249768/9869b4f8-3a7b-11e4-82f2-6c96b33075cc.gif)

It was working, and suddenly it stopped. Any idea how to fix it?

**Comment by riskers** [comment]
Yeah , same problem....

**Comment by oklai** [comment]
Remove this directory `%userprofile%/.koala`, then restart Koala.

**Comment by riskers** [comment]
Yeah , it had solved perfectly
