### ISSUE TITLE
windows 7 x64 Convert CSS images to base64 not work

### ISSUE THREAD

**Issue by zwlcoding** [oklai/koala#302]
I'm using less, After compiling did not produce changes

**Comment by claudiofrs** [comment]
yep, I still have the issue. I'm using sass with .scss filename. Won't compile image to base64.

**Comment by oklai** [comment]
Convert CSS images to base64 with `?base64` param, this feature only supports css.
But you can also make this on LESS or Compass.
LESS: `background-image: data-uri('../data/image.jpg');`
Compass: `background-image: inline-image('../data/image.jpg');`
