### ISSUE TITLE
App won't run on ubuntu 14.04

### ISSUE THREAD

**Issue by radeftw** [oklai/koala#305]
Hi, I installed your app, 64bit version on ubuntu 14.04, however when I start the app nothing happens, it doesn't start.

**Comment by Kecoey** [comment]
@honucreative Thank you so much!! Worked perfectly.

**Comment by kmshub** [comment]
@honucreative Thank you, magic man!

**Comment by sayhellotovanessa** [comment]
It helped me with Ubuntu 16!
Thank you.

**Comment by YellowLabIT** [comment]
Helped me too with Ubuntu 16
