### ISSUE TITLE
Stylus Support 

### ISSUE THREAD

**Issue by Abhinav1217** [oklai/koala#315]
How to add stylus support in this application?  
I tried to follow instruction from https://github.com/oklai/koala/wiki/How-to-create-a-compiler-extension but still not being able to add stylus support in it.  

Stylus version 0.49.2  
Node version 0.10.33 installed using nvm v0.17.3  
Fedora 20

**Comment by indiluk** [comment]
Hi, just wrote a tiny stylus plugin for Koala, pull at https://github.com/indiluk/koala-stylus/tree/master

**Comment by zaygraveyard** [comment]
Added to the [List of compiler extensions](https://github.com/oklai/koala/wiki/List-of-compiler-extensions) page.

**Comment by Abhinav1217** [comment]
Thanks guys.  Although I have moved to command line build tools, I would still love to recommend this to  some of my friends.
