### ISSUE TITLE
Incorrect characters for smart quotes

### ISSUE THREAD

**Issue by ricardozea** [oklai/koala#316]
First, let me say that Koala rox.

Second, here’s an issue I’m having:

I have this in my SCSS for smart quotes: 

`blockquote, q { quotes: "“" "”" "‘" "’"; }`

Which gets compiled to these bunch of incorrect characters:

`blockquote, q { quotes: "ΓÇ£" "ΓÇ¥" "ΓÇÿ" "ΓÇÖ"; }`

Regards,

PS. What are “smart quotes”? Here you go: http://smartquotesforsmartpeople.com/

**Comment by OksanaRomaniv** [comment]
Have same problem with this char - “
@charset "utf-8" doesn't solve this for me. Any other suggestions? 
Thank you!

**Comment by ricardozea** [comment]
I don't know your build but try adding `@charset "utf-8"` to the main SCSS file. If that fails, try adding it to all files including partials.
