### ISSUE TITLE
Error starting Koala

### ISSUE THREAD

**Issue by skrelo** [oklai/koala#320]
All of a sudden whenever I try to start Koala, I get this error:

--error--
C:\Program Files (x86)\Koala\app\scripts\patch.js
Uncaught TypeError: Cannot read property 'appVersion' of null

I close the error and it shuts down Koala, I try to start up Koala again and all it gives me is the Koala window that is totally white. I close this down and try to start Koala, and get the error again. It alternates between the white window and the error box

Windows 7 SP1
64GB RAM
500 GB SSD

**Comment by santiramirez** [comment]
@oklai You're a genius!

**Comment by marcelschiering** [comment]
Helped me too. thanks!

**Comment by DrevanTonder** [comment]
Helped me too. Almost **gave up** on Koala.
Using Windows 10.

**Comment by ajayidavid99** [comment]
like magic
