### ISSUE TITLE
disable auto compile

### ISSUE THREAD

**Issue by achavazza** [oklai/koala#339]
where is an option to disable "auto compile files when project added"? a feature recently added in 2.0.4

I use multiple imports & mixins on .less files, that compile on a single .css file
but with that feature makes my files a mess

**Comment by robwent** [comment]
+1 for disabling this and adding an option to general settings

**Comment by hkulekci** [comment]
Are there any development about this issue? +1 to adding an option to general settings.

**Comment by smth** [comment]
+1

Having to turn on auto-compile manually is far less annoying than having to delete a whole bunch of CSS files.

**Comment by englishextra** [comment]
Yeah-yeah, I have js and css folder for every typical pages
libs-
     template1 - 
                      css
                      js
     template2 - 
                      css
                      js

So I add libs as a project folder an then I switch to CSS link at the bottom of Koala UI I see list of css file of every template folder not js so I celect them and in right context menu choose COMPILE and the hell my js file also get minified with UglifyJS library which I dont actually  need.

Well autocompile was not checked in UI but nevertheless JS files get compiled very confusing

And oh by the way UglifyJS is not the best choice for me and probobaly for many other devs

I guess they would prefer google closure or more safe JSMin by Crockford

**Comment by jleee** [comment]
+1 

Any chance to get this fixed within this year?

**Comment by zaygraveyard** [comment]
Merging with #367
