### ISSUE TITLE
Possible to have multiple output folders?

### ISSUE THREAD

**Issue by Guitarkalle** [oklai/koala#36]
I would like my less to compile to several output folders at the same time. Would this be possible to fix?

**Comment by justin2hale** [comment]
I have another solution for this.
create a projects folder as a sister folder to your main sass folder:

-sass/
--style.scss
-projects/
--project1/
---style.scss
---koala.config.json

In your project1 style.scss, @import the style.scss from your sass/scss folder.
In the koala.config.json file, set your dest: "[destination]" to wherever you want your .css and .map to be created for your new project.

Recreate this process as many times as you need for each project that you want to share the same output.
