### ISSUE TITLE
CFBundleIdentifier in Info.plist on OS X not unique (causes issue with Munki deployment system)

### ISSUE THREAD

**Issue by jps3** [oklai/koala#362]
I would very much like to include Koala.app as part of our automated update check and deployment system for my Mac labs on campus, but there is a minor hitch that is preventing this from working easily at the moment.

On the OS X version of Koala.app, in its `Info.plist` file, the key `CFBundleIdentifier = com.intel.nw` is also the same exact identifier as that used by Wacom for their `Wacom Help.app` included with their tablet drivers. (Possibly other software as well, but that is just the conflict I have encountered). This conflict effectively causes an update system such as Munki to skip over installing Koala because there is already the same `CFBundleIdentifier` for another app bundle, especially as the `CFBundleShortVersionString` currently evaluates as being less than that for `Wacom Help.app`. The `CFBundleIdentifier` name conflict could also cause odd issues when configuring to automatically remove software as well.

I realize in the larger scheme of things while developing this software this is low on the list of priorities. However, if it is simple and easy for you to change/fix/add your build systems such that `CFBundleIdentifier = com.intel.nw.app.Koala` (or whatever) it would be _greatly_ appreciated.

Thank you for your consideration. Also: nice app!

**Comment by zaygraveyard** [comment]
Fixed in the recent versions
