### ISSUE TITLE
File permissions for Koala.app/Contents/Resources/app.nw needs to be 0755 not 0700

### ISSUE THREAD

**Issue by jps3** [oklai/koala#363]
The directory `Koala.app/Contents/Resources/app.nw` in v2.0.4 currently is set to 0700 (only accessible to the owner) which causes issues on multi-user systems, such as academic labs.

If changed to 0755 it fixes the issue.

Thanks.

**Comment by jps3** [comment]
(I should have mentioned that this is for the *OS X* version of the app just to be clear.)

**Comment by Glutnix** [comment]
We're having a similar issue in our OSX academic lab, and @jps3's solution worked for us. Please test the app with a non-administrator :)
