### ISSUE TITLE
Help in app availability homebrew-cask

### ISSUE THREAD

**Issue by illusionfield** [oklai/koala#370]
I would like to ask your help that the application can be available in the "homebrew-cask" project. To this a direct official download url is needed.
Here you can find problem in more detail: https://github.com/caskroom/homebrew-cask/pull/9373
I hope you can help in it. If you need any help from my side solving this problem do not hesitate contacting me.
Thanks in advance,

**Comment by zaygraveyard** [comment]
Hello @illusionfield,
Still interested in adding Koala to homebrew-cask?
Now there is a direct download link for the dmg, will it work?
Thanks
