### ISSUE TITLE
Concatenate Multiple JS to One like in Grunt

### ISSUE THREAD

**Issue by surjithctly** [oklai/koala#387]
I'm using Koala for Windows, and loving it, This is the one feature missed in this.

Any Chance to Concatenate multple JS files in to One, Like in Grunt? Also to watch changes in files and compile automatically same as in Sass or Less. 

Any way to Integrate Grunt tools in Koala? Its seems very hard to use CLI for Grunt. But its really useful.

**Comment by oklai** [comment]
You can use the combine feature [append a file at the end of another file](https://github.com/oklai/koala/wiki/JS-CSS-minify-and-combine#append-a-file-at-the-end-of-another-file)

e.g: mian.js
```
// @koala-prepend "file1.js"
// @koala-prepend "file2.js"
// @koala-prepend "file3.js"
// ...
```
