### ISSUE TITLE
How about adding Comb to compiler?

### ISSUE THREAD

**Issue by steviss** [oklai/koala#390]
The title kinda makes it self explanatory. Could you add this feature? It would be a nice one to add :).

http://csscomb.com/

**Comment by oklai** [comment]
The main function of Koala is to watch the file which need compile after
modified and compress files, so I think the Comb feature does not fit into
Koala.

Cheers.

2015-03-24 22:04 GMT+08:00 Stefan Stevic <notifications@github.com>:
