### ISSUE TITLE
Koala is slowing down our local network

### ISSUE THREAD

**Issue by e-novinfo** [oklai/koala#397]
Hi!
First of all, we'd like to say that Koala is a fantastic application that we use everyday!
Unfortunately, since a few weeks (maybe since Koala's last update), we have a problem with this app that we don't really understand.
We are a small team of WebDesigners (working on Windows 8) and all the files of our projects a stocked on a server (Ubuntu) that we share. We are all working on different projects and so we all have Koala open permanently with auto compiling mode activated. Everything was fine until a few weeks ago. We noticed that when Koala is open, every action that we do on the server is horribly slowed down. Not only with our IDE (Atom or NetBeans), but with every software that is working with our local network. If we close Koala, everything speed up and we are fine again.
What can we do about it?
Many thanks!

**Comment by jvanasco** [comment]
You need to upgrade your server and network, or stop abusing this software with "auto compile"

Every one of your computers has your server locally mounted.  Auto-compile requires each machine constantly checking the files and looking for updates, then reading all the files and writing new ones.  That's a lot of processing and traffic.
