### ISSUE TITLE
ubuntu 13 (64bit) error

### ISSUE THREAD

**Issue by ghost** [oklai/koala#40]
info:
/usr/share/koala/koala: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory

**Comment by Xmetalfanx** [comment]
still seems to be an issue (Ubuntu Mate 16.10 here) ... that 

`cd /lib/x86_64-linux-gnu/`

then 
`sudo ln -s libudev.so.1 libudev.so.0` fixed it though ... had to come here to figure out why i was getting that error though
