### ISSUE TITLE
---uncaughtException--- TypeError: cannot read property    Error

### ISSUE THREAD

**Issue by SenthilRoyann** [oklai/koala#408]
---uncaughtException---
TypeError: cannot read property
F:\wamp\www\Projects\_\... of null

I tried Re-install but its throws the same error... :(
How to solve it...?

**Comment by oklai** [comment]
Hi,
Just delete the folder `%USERPROFILE%/.koala` , then reopen Koala.

**Comment by jelleverzijden** [comment]
Same problem, but i can't find the file you mention above?
![uncaught](https://cloud.githubusercontent.com/assets/13240330/8575165/db3514de-259a-11e5-8687-2ba7bd38a5de.jpg)

**Comment by jelleverzijden** [comment]
Found it :)

**Comment by grafxflow** [comment]
Still works great :)

**Comment by raja1112** [comment]
its working great job thax dude

**Comment by Kovalchyn** [comment]
I can`t find this file! HELP

**Comment by itsbrunocampos** [comment]
Hey @Kovalchyn, if you're using a macOS, that's in:
Macintosh HD > Users > {yourComputersUserName} > Library > Application Support > Koala > UserData
Note: The Library folder is hidden, so use the shortcut (Shift + Command + .) to reveal it.
