### ISSUE TITLE
Koala compiler not working in windows

### ISSUE THREAD

**Issue by shmdhussain** [oklai/koala#43]
I need to compile LESS to CSS file. i installed the koala GUI application in my windows7 PC. but not able to see the app window when i clicked open the Koala app. But Koala.exe is there in my task manager's process tab. Please help me in this . Thanks in advance.

**Comment by OlyaYuzefiv** [comment]
![image](https://user-images.githubusercontent.com/51438145/59992209-4a07fc00-9653-11e9-8cbb-9ef661b492b0.png)

**Comment by OlyaYuzefiv** [comment]
help please

**Comment by chrisbo** [comment]
It is trying to do a clean install, so go ahead.

**Comment by manoj-gautam85** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/42959557/121300060-f06a6c00-c913-11eb-941c-1db7349e48ec.png)

Hello friends,
Anybody know how to fix this problem. I want to delete a file in the list of projects but it's not working. I have already deleted and uninstalled koala in my system then again install it but facing the same issue with that.
