### ISSUE TITLE
Change location of compiled css

### ISSUE THREAD

**Issue by cherihung** [oklai/koala#45]
Compiled CSS files are now saved to the same folder as their preprocessor files. But I would like to have all css files be saved to another location. 

Is there an existing setting to do this?  Thanks! This tool is pretty awesome.

**Comment by Gursimranjot** [comment]
Write click on the that scss file for which you want to change the path.Please check the screenshot for further details
![untitled](https://cloud.githubusercontent.com/assets/5369469/23360713/f2c8dd14-fd12-11e6-83d9-990b4ec472f4.png)
