### ISSUE TITLE
Suggestion - don't autocompile on directory drop

### ISSUE THREAD

**Issue by luison** [oklai/koala#452]
Happily been using your app for a few weeks, a suggestion for future versions... if I drag a directory to it don't start autocompiling every single less/sass file found as this 9 out of 10 is not the case you want, but normally one or 2 files on that directory, the rest being vars or modules. I understand you might already avoid files starting with "_" but even so I find it more sensible to add directory, choose files to autocompile and then compile.
Just an idea.

**Comment by bwente** [comment]
+1

**Comment by theodorocaliari** [comment]
+1

**Comment by schwabsimon** [comment]
+1

**Comment by MitchellBouwman** [comment]
+1

**Comment by digitaloutback** [comment]
+1

**Comment by henrix343** [comment]
+1

**Comment by schwabsimon** [comment]
Ich bin bis am 01. September in den Ferien. Wenden Sie sich bitte an
    die offizielle Adresse der Escapenet: info@escapenet.ch
    -- 
Freundliche GrÃ¼sse
Simon Schwab

--
Simon Schwab | Escapenet GmbH
www.escapenet.ch 
+41 52 235 07 00/07

Web, Design, Druck, Verlag
Zusammen mit der Mattenbach AG 
bieten wir Ihnen jetzt alles aus einer Hand
www.mattenbach.ch

**Comment by luison** [comment]
I understand from @oklai the developer that koala is not "completely" dead and he is planning to release an update. Please keep this small feature in mind and make dropped or added folder by default "not autocompile" so one has to decide which ones to select for that. The only really annoying feature I don't like about Koala.

**Comment by MitchellBouwman** [comment]
I think a lot of people already moved to Prepros.io ;)

**Comment by zaygraveyard** [comment]
Option added in v2.2.0
