### ISSUE TITLE
How to auto-compile after I change "combine import" files ?

### ISSUE THREAD

**Issue by sandrina-p** [oklai/koala#479]
So imagine I have this 3 files:
file-one.css
file-two.css
file-three.css

and I want to merge them in one single file, all-files.css with @import. then on koala i select "combine import to the .min.css file. So far so good.

Now, imagine I change the file-two.css and save it. All-files.css didn't auto-compile and it stays with the older version of file-two.css. How do I do to Koala recognize when I update a file, and it updates all the files that have that file I changed. Did I make it clear?

p.s. The question remains the same for css @import, and javascript with @koala-prepend.

Thanks a lot

**Comment by himanshuapril1** [comment]
You can better convert those files in `.SCSS` extensions and then import all files with in one and set it to auto-compile. Going this way, each time you make any change in any scss file it'll automatically update and compile all your files into single `CSS` file showing all the changes you made.

**Comment by sandrina-p** [comment]
Thanks! And what about .js files?

No dia domingo, 24 de janeiro de 2016, Himanshu Aggarwal <
notifications@github.com> escreveu:

**Comment by zaygraveyard** [comment]
Still an issue?

**Comment by sandrina-p** [comment]
Well, I left Koala and started using [Gulp](http://gulpjs.com/). After a while I moved on to [Webpack 2](https://webpack.js.org/), so no, it's not a issue anymore for me x)
