### ISSUE TITLE
Koala not start on Centos 7

### ISSUE THREAD

**Issue by nturns** [oklai/koala#489]
Ruby exits without starting koala. Using the command "ruby -v koala" returns lots of warnings, but no errors. This is on a fresh install of Centos 7 64-bit which came with ruby 2.0.0p598 installed. Ruby test program prints "Hello World." I did a symbolic link "ln -s libudev.so.1 libudev.so.0" but that changed nothing. Koala installed with "gem install koala" Tail end of install with gem printed these warnings, but otherwise it seems to be installed.
-----------------`
Parsing documentation for koala-2.2.0
Installing ri documentation for koala-2.2.0

*\* (gedit:1274): WARNING **: Set document metadata failed: Setting attribute metadata::gedit-position not supported

(gedit:1274): dconf-WARNING **: failed to commit changes to dconf: The connection is closed
5 gems installed
`-----------------

Any ideas?

**Comment by zaygraveyard** [comment]
Koala is not written in Ruby nor is it a Ruby gem.
You should just run `koala`
