### ISSUE TITLE
doesn't works on ubuntu

### ISSUE THREAD

**Issue by sebassdc** [oklai/koala#491]
I already installed the .deb package and doesn't start

**Comment by beat** [comment]
I confirm this too. When starting it tries to use an outdated version of a library that got removed in Ubuntu 14.04 almost 2 years ago:
```
$ koala
/usr/share/koala/koala: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
```

**Comment by beat** [comment]
Update: Once I read the FAQ, which leads to wrong solution but has a comment to better solution:
https://askubuntu.com/questions/288821/how-do-i-resolve-a-cannot-open-shared-object-file-libudev-so-0-error/593420#593420
It now loads, but with following error/warning:

```
$ koala
[29486:0217/182757:ERROR:zygote_host_impl_linux.cc(144)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
```

Still believe that packages should run on recent linux systems without requiring manual libraries installs, but thanks to open-source, at least there is a solution :-)

Btw, it would be great to have a debian/Ubuntu repository for easy automated upgrades ;-)

**Comment by kossak31** [comment]
check this `https://github.com/oklai/koala/issues/499`
it works for me now

**Comment by JoseBarakat** [comment]
This happened to me right out of the box:
```
~$ koala
/usr/share/koala/koala: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory
```
Searching for `libudev`:
```
~$ ls /lib/x86_64-linux-gnu/libudev*
/lib/x86_64-linux-gnu/libudev.so.0  /lib/x86_64-linux-gnu/libudev.so.1.6.5
/lib/x86_64-linux-gnu/libudev.so.1
```
If `libudev.so.0` points to an older version (ex. `libudev.so.1.3.5`), just delete it like this:
```
~$ sudo rm /lib/x86_64-linux-gnu/libudev.so.0
```
And recreate the symlink again so it points to correct version (replace `libudev.so.X.X.X` for current version):
```
sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1.6.5 /lib/x86_64-linux-gnu/libudev.so.0
```
Now that symlink exists, you can launch Koala...
```
~$ koala
[26122:1127/225913:ERROR:zygote_host_impl_linux.cc(144)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[26122:1127/225913:INFO:gpu_info_collector_x11.cc(78)] NVCtrl extension does not exist.

```
![captura de pantalla de 2016-11-27 23-00-05](https://cloud.githubusercontent.com/assets/15618933/20655914/46defbb0-b4f5-11e6-970d-e6b5222f8a73.png)

**Comment by zaygraveyard** [comment]
Thank you @JoseBarakat
