### ISSUE TITLE
software is no opening

### ISSUE THREAD

**Issue by ghost** [oklai/koala#496]
having problem I installed the software. but it's not opening..

**Comment by rudiruhl** [comment]
@ayanwebtech try to reinstall the software. Any error-messages??

**Comment by ayanwebtech** [comment]
i already did that two times.

**Comment by GlupiJas** [comment]
is that ubuntu  os by any chance ?

**Comment by zaygraveyard** [comment]
@ghost if you are using ubuntu try https://github.com/oklai/koala/wiki/Unable-to-run-Koala-in-Linux

**Comment by zaygraveyard** [comment]
Closing for now, please reopen if the problem persists
