### ISSUE TITLE
lib dont found libudev.so.0

### ISSUE THREAD

**Issue by kossak31** [oklai/koala#499]
TRY RUN KOALA
x@pc:~$ koala
/usr/share/koala/koala: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory

WHERE IS THE LIB?
x@pc:~$ locate libudev.so
/lib/i386-linux-gnu/libudev.so.1
/lib/i386-linux-gnu/libudev.so.1.5.0

CREATE A LINK
x@pc:~$ sudo ln -s /lib/i386-linux-gnu/libudev.so.1.5.0 /lib/i386-linux-gnu/libudev.so.0
x@pc:~$ koala

**Comment by kossak31** [comment]
it was my soluction

**Comment by andrewelkins** [comment]
Worked for me as well. If you're using the 64 bit version make sure to change the path to reflect that.

`sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1.3.5 /lib/x86_64-linux-gnu/libudev.so.0`
