### ISSUE TITLE
Support "Jade"

### ISSUE THREAD

**Issue by moongod101** [oklai/koala#506]
Jade is awesome too :)

jade will do the HTML job but make it so clean,just like sass :)

Official website: [Official Web](http://jade-lang.com/)

--Thank you--

**Comment by jespardk** [comment]
I think this extension takes care of Jade-support already:
https://github.com/oklai/koala/wiki/List-of-compiler-extensions

**Comment by moongod101** [comment]
Thank you very much!!!!

**Comment by panphora** [comment]
Thank you! I've been wanting this for a month and had no idea it was so easy!
