### ISSUE TITLE
--uncaughException--

### ISSUE THREAD

**Issue by tommaso-bissoli** [oklai/koala#508]
Hi there everybody,

at a certain point, after an edit to a particular "_commons.scss" sass file in my sass project, Koala started to crash and to crash my PC too...

I renamed that particular damn "__commons.scss_" file with another name and Koala stopped crashing (and my pc too) but I started to get the alert of which I report the message at the and of this post every time I compile ma final scss file of my project.
The renamed ex "_commons.scss" file absolutely has nothing strange inside of it but just some @import rules...

As I wrote, this problem started "at a certain point" in time after I had already started my sass project from long time and that particular "_commons.scss" file had never caused any sort of problems...

I sospect Koala could has been infected by a kind a virus... is it possibile to you?
I tried to disinstall Koala and reinstall it but nothing changed...

Here is the message of the alert I get after compiling my final .scss file:

--uncaughException--
TypeError: Cannot read property
'D:\Web\Sites\skyonline\sass\commons_commons.scss' of null
    at C:\Program Files

Button "OK"

Can anyone help me please? :-)
Thank you.

**Comment by zaygraveyard** [comment]
Is this still an issue?

**Comment by tommaso-bissoli** [comment]
Hi zaygraveyard :-)
I purshased Prepos to solve the problem ^^
I don't know it's still an issue but I guess yes ^^

**Comment by zaygraveyard** [comment]
@tommaso-bissoli thanks for the update 😄 
And sad to see you go 😢

**Comment by tommaso-bissoli** [comment]
Yes sorry very satisfied... ^^
But as a free solution I still advise Koala ;-)
I think a strange and rare issue happened to me :-)
