### ISSUE TITLE
filewatcher.js问题

### ISSUE THREAD

**Issue by WangYang-Rex** [oklai/koala#513]
一直alert cannot read property of null at filewatcher.js:133:30
单独编译某个文件都是OK的，打包压缩的时候就会报错，卸载重装2次一样的问题

**Comment by WangYang-Rex** [comment]
I find the solution:
Remove this directory %userprofile%/.koala, then restart Koala.
restart Koala,

**Comment by zaygraveyard** [comment]
@WangYang-Rex Is this issue been resolved? Can we close it?
