### ISSUE TITLE
在用sublime对scss文件进行编译的时候出错了，麻烦大神看看是什么原因！感谢！！！

### ISSUE THREAD

**Issue by sunlig-lau** [oklai/koala#514]
Encoding::CompatibilityError: incompatible character encodings: GBK and ASCII-8BIT
  Use --trace for backtrace.
不知道怎么去解决这个问题 ，麻烦哪位指点一下！！谢谢！！！！！
![image](https://cloud.githubusercontent.com/assets/18575247/14675745/0e1043c2-073d-11e6-87ec-6391e77ce54a.png)

**Comment by luyaohua2016** [comment]
编码问题，代码截图看看

**Comment by fh345392977** [comment]
统一charset

**Comment by fredwei** [comment]
在scss文件顶部加@charset "utf-8";

**Comment by JessieBean66** [comment]
是不是因为文件路径中有中文字符，才报这个错？我加上了@charset "utf-8";在文件顶部，可是仍然报错。有哪位仁兄加上后解决了问题的吗？

**Comment by 1475142232** [comment]
是不是因为文件路径中有中文字符，才报这个错？我加上了@charset “utf-8”;在文件顶部，可还是仍然报错。有哪位仁兄加上后解决了问题的吗？

**Comment by sunlig-lau** [comment]
delay
