### ISSUE TITLE
Inconsistent indentation: 4 spaces were used for indentation, but the rest documents was indented using 1 tab

### ISSUE THREAD

**Issue by Ilya-ya** [oklai/koala#516]
Inconsistent indentation: 4 spaces were used for indentation, but the rest documents was indented using 1 tab
![error](https://cloud.githubusercontent.com/assets/8741799/14765951/f24a644c-0a11-11e6-8642-6b78cdb88831.jpg)

**Comment by agarwalakash** [comment]
You should use tab instead of spaces. remove spaces and use tab.
