### ISSUE TITLE
求助大神们，Windows下编译scss报错，但是编译成功......

### ISSUE THREAD

**Issue by DoopSky** [oklai/koala#521]
![1](https://cloud.githubusercontent.com/assets/8330408/16017846/5531bc42-31d4-11e6-8e48-6c6ee3cf9741.jpg)

我在使用Koala编译scss时出现了如上图所示的错误。
我在koala中选择了自动编译，每次写编辑完scss保存时都会出现上图所示错误。
但是重新编译一次又提示“success”......

我的环境：
Windows 7 Ultimate 64 bit
编辑器使用的Sublime Text

在这里提前谢谢大家的帮助！

**Comment by iVanilla** [comment]
我是遇到这个问题
Individual stylesheets must be in the sass directory.

**Comment by Kuohao-wu** [comment]
这个问题搞得我很烦啊，重装不行，删除.koala文件也不行，每次保存都会提示错误，只报个路径。

**Comment by zaygraveyard** [comment]
Still an issue?
