### ISSUE TITLE
Compile a .css AND a .min.css file simultanously

### ISSUE THREAD

**Issue by chwebo** [oklai/koala#528]
Is it possible to do both at the same time?
I'm writing much code in different .scss files and I always want to have an extended css file to check the compiled code and have a compressed file to upload to the websites. Until now, I have always changed the path and the compile method, but it would be very timesaving if I could ask Koala to compile a compressed version to a path and compile an expanded version to another path.

**Comment by PhilipsEkuma** [comment]
It is possible.
* In your `koala-config.json` file of your project, make sure to adjust the part as follows:

```json
	// Add the ignore rules that Koala will not search them.
	// e.g. ["*.json", "*.txt", "test", "path/libs"]
	"ignores": ["*.css"],
```

If you have .css in the ignores property, remove it:
`"ignores": []`

* Then open Koala app.

![css-tab-koala](https://cloud.githubusercontent.com/assets/5754982/17031616/e96c9962-4f6c-11e6-8795-dedd5aa5f9a1.png)

* Click the edit icon to change the **Save as** path and file name.
* Click the **CSS** tab.
* Adjust the following settings to your preference. Be sure to keep **Auto compile** checked.

![auto-compile-minification-koala](https://cloud.githubusercontent.com/assets/5754982/17031655/296d8710-4f6d-11e6-9cc0-311892bde01c.png)


That should do it for you I hope.

**Comment by chwebo** [comment]
Awesome! Thank you very mucht!!
