### ISSUE TITLE
Is Koala project abandoned?

### ISSUE THREAD

**Issue by Alecto** [oklai/koala#537]
I see that for a long time did not have any program updates. The author is not responding issues.
Therefore, interested in the question: this project abandoned?
if yes - can be supported by a fork there?
there may be a good alternative to the GUI?

**Comment by raknjak** [comment]
I must be, another Github fail.

**Comment by zaygraveyard** [comment]
This project is not abandoned, but I don't know it's in development anymore
But I'll try to maintain it, and maybe one continue to develop it

**Comment by Alecto** [comment]
whether you maintain an alternative branch?
where can we keep up to date koala compiler?
Thank you.

**Comment by zaygraveyard** [comment]
> whether you maintain an alternative branch?

I currently don't have an alternative branch
I want to replace [NW.js](http://nwjs.io) with [electron](http://electron.atom.io), but unfortunately I don't have enough free time.
I'll update this issue there are any changes.

> where can we keep up to date koala compiler?

Koala is not a compiler, it uses known compilers
So compilers can be updated independently from Koala
As for the latest version of Koala, for now there are no new updates

I hope this helped you

**Comment by Alecto** [comment]
how can i update compilers for koala?

**Comment by zaygraveyard** [comment]
@Alecto If by compilers you mean `lessc` and `sass`, then you can simply install whatever version you want on your system and tell Koala to use it:
1. Open the "Settings" of Koala
2. Select the compiler section on the left (ex. LESS)
3. In the "Advanced Settings" section on the right, check the "Use the system .. compiler" checkbox
4. Enter the full path to the compiler in the field below the checkbox.

**Comment by Alecto** [comment]
i use SCSS, so i need to intall RUBY? and set the path to it folder?

**Comment by zaygraveyard** [comment]
You probably already have Ruby installed, so I suggest verifying before install it.
Than you need to install [`sass`](http://sass-lang.com/install).
And finally you can try to leave the path field empty (it will be set to `sass` by default), if it doesn't work then you need to find the full path to `sass` and put that (the path) in the field.

**Comment by Alecto** [comment]
thank U.

**Comment by zaygraveyard** [comment]
I'm glad it helped

**Comment by Alecto** [comment]
zaygraveyard, I have a question about the autoprefixes.

I understand that they need to be updated periodically in order to understand the modern browsers, and how many versions should be supported.

but if the koala is not updated, then this option maybe not correct.
Besides, I could not find where to change the number of versions for autoprefixes.

I tried an alternate compiler Prepros.

it's awful. permanent errors accessing files during compilation. sometimes it compiles not all changed files in project... etc. very bad work!
koala is stable, errors when compiling clear, easily corrected.

maybe you could update the koala with the latest libraries SASS LESS and autoprefixes?

**Comment by zaygraveyard** [comment]
@Alecto you are correct. I will try to update them soon and cut a release.
Usually @oklai makes the releases (since I'm just a collaborator), but as he is no longer responding I'll try to do it.

**Comment by shikkaba** [comment]
Any luck on this?

**Comment by zaygraveyard** [comment]
I updated nwjs to the latest version and I'm working on creating a release (the packaging)
Once I successfully package it for Windows, OS X, and Linux I'll update the packages (LESS, SCSS, ...) and do a release

**Comment by RangerGH** [comment]
In reference to the question about needing Ruby by Alecto (above). I do not have Ruby installed and I use SCSS so do I still need to have Ruby?

Thanks.

**Comment by zaygraveyard** [comment]
@RangerGH you only need to install Ruby if you want to install SCSS on your system. Koala includes a version of Ruby which is used to run SCSS without having to install it on the users system.
But @Alecto found that the version of SCSS included in Koala was old so I suggested that he installs the new version on his system independently from Koala and tell Koala to use it.

**Comment by RangerGH** [comment]
Currently I'm using npm node-sass to compile my SCSS via gulp so I don't need Ruby.  I guess the question I should really be asking is can I use node-sass and the npm compilers.  I really don't want or need Compass or Ruby on my system - nothing against them but I'm just using npm stuff now.  I'd like a GUI that is like CodeKit but I'm not on a Mac but Linux.

Thanks.

**Comment by zaygraveyard** [comment]
`node-sass`'s CLI seams to be different from `sass`'s.
But I wrote an adapter script that I think will allow it to work.
Normally you would need save the script somewhere on your system and make it executable.
Then tell Koala to use it.
**This code is not tested**
Let me know if you find any problems.

```bash
#!/bin/bash

ARGS=();
scss=false;

while [[ $# -gt 0 ]]
do
    case "$1" in
    --load-path)
        ARGS+=("--include-path");
        break;
        ;;
    --require)
        # not implemented in node-scss
        break;
        ;;
    --style)
        ARGS+=("--output-style");
        break;
        ;;
    --scss)
        scss=true;
        break;
        ;;
    --sourcemap=none)
        break;
        ;;
    --sourcemap=*)
        ARGS+=("--source-map");
        break;
        ;;
    --debug-info|--line-numbers|--line-comments)
        ARGS+=("--source-comments");
        break;
        ;;
    *)
        ARGS+=("$1");
        ;;
    esac
    shift;
done

if [ "$scss" = false ];
then
    ARGS+=("--indented-syntax");
fi

exec node-sass "$ARGS"
```

**Comment by RangerGH** [comment]
Thanks.  I'll test it out.  Yes, node-sass has different command line options then sass does.

**Comment by RangerGH** [comment]
Downloaded koala from http://koala-app.com/ which I assume is the correct location.  It shows a more recent koala then GitHub at https://github.com/oklai/koala//  It appears Koala is not dead since you are responding but the changes in GitHub are 3-4 years old so what is the status of the project.  Is koala-app.com the same as the github files?

If I run ./koala after untarring I get libudev.so.0 not found.  I do have some libudev.so.  Do I need to create a symlink or am I missing a piece?

/usr/lib/libudev.so.1
/usr/lib/libudev.so.1.6.4
/usr/lib64/libudev.so.1
/usr/lib64/libudev.so.1.6.4

Thanks.

**Comment by RangerGH** [comment]
Created a symlink and got it started so I'll work with it.  Thanks.

**Comment by shikkaba** [comment]
@zaygraveyard Any update on packaging?

**Comment by zaygraveyard** [comment]
Sorry for the delay (I've been very busy) 😓 
The mac package is good to go, but I still need to test the windows package and the linux ones.
I'll try to do it tomorrow and let you know.

**Comment by zaygraveyard** [comment]
I have successfully packaged Koala for Win 32bit, macOS 64bit, Debian 32/64bit, and RedHat 32/64bit (although I have not tested installing the ".rpm" yet).
I'll try to update the compilers tomorrow and do a release.

**Comment by shikkaba** [comment]
Thank you for your hard work in trying to get an update out. Please let us know when you can do a release. :)

**Comment by falzard** [comment]
using koala for years, never updated it, it's a bit worrying me but I learned here that I can update the compilers manually, that's nice

**Comment by foal** [comment]
@zaygraveyard Any updates about the release? Thank you!

**Comment by zaygraveyard** [comment]
🎉 Koala 2.1.0 is here 🎉 

Thank you all for sticking around 😄 
I haven't had time to do thorough tests, so if anyone find problems or bug, please let me know 😅

I'll try to update the website soon
The latest version of LESS is 2.7.2 (and 3.0.0-alpha.2) which has different API and CLI, I'll update it soon

Changes:
* change the default value of maxBuffer #162
* support for AutoPrefix Config on CSS, LESS and Sass
* fix backslashes in map source paths on Windows
* update `node-webkit` to the latest version of `nwjs`
* update LESS(@1.7.5), Sass(@3.4.23), Compass(@1.0.3), CoffeeScript(@1.12.4), uglify-js(@2.8.21), and clean-css(@4.0.10)

Download from:
* [Windows](https://drive.google.com/open?id=0B-tHQW4o9rnYak54ak1MWk9FWjQ)
* [macOS](https://drive.google.com/open?id=0B-tHQW4o9rnYTVlPampRdmVSeEE)
* [Linux 32 bit](https://drive.google.com/open?id=0B-tHQW4o9rnYTUhBWXdoUXhWVWc)
* [Linux 64 bit](https://drive.google.com/open?id=0B-tHQW4o9rnYWmtqVTlTSW11cjA)
* [Debian 32 bit](https://drive.google.com/open?id=0B-tHQW4o9rnYNlpTZ0U4SjhCODg)
* [Debian 64 bit](https://drive.google.com/open?id=0B-tHQW4o9rnYUmxLa05fbWFsUEE)
* [RPM 32 bit](https://drive.google.com/open?id=0B-tHQW4o9rnYM084RlV5V3RzQTA)
* [RPM 64 bit](https://drive.google.com/open?id=0B-tHQW4o9rnYWVNBT3JLNmtKOTg)

**Comment by falzard** [comment]
"support for AutoPrefix Config on CSS, LESS and Sass"

But it is already a setting for me. Anyway, thank you, I'm downloading it right now and I'll report to you. You should create a github repository though.

**Comment by zaygraveyard** [comment]
> support for AutoPrefix Config on CSS, LESS and Sass

I just copied it from a commit that was already on the `master` branch but after the `v2.0.4` so it's possible that @oklai updated the app binary without creating a release.

> You should create a github repository though (with a release section :) )

For now I'll update this repo, because the website is linked to this repo (plus all the issues are on this one).
But eventually I'll fork this project (I was thinking of doing it when I replace `nwjs` with `electron`)

Thank you for the support 😄

**Comment by falzard** [comment]
But you didn't update this repository :P if you do many people will test the new update. I have nothing to do regarding web dev for now so I'm not going to test it for a while (and I'm used to the old koala with the old LESS so I am not really aware of what to test). I just want to support you with my words :P

**Comment by zaygraveyard** [comment]
I updated this repo 😄 
And trying to update the website now
BTW this version of Koala uses the same major version of LESS (1.x.x) so it's still the same LESS (at least for now 😉 )

**Comment by zaygraveyard** [comment]
Updated the website 🎉

**Comment by zaygraveyard** [comment]
Closing this issue because the answer, at least for now, is **no** it not abandoned (not by me that is).
Feel free to reopen this issue if the question arises again.

**Comment by falzard** [comment]
Just wanted to say that I tried it and it works perfectly.
