### ISSUE TITLE
Unable to install into Ubuntun 16LT

### ISSUE THREAD

**Issue by jzhang28** [oklai/koala#538]
I tried both 32 and 64 bits, but none of them are working. 64bits is able to be installed successfully while unable to start. 32 bits is failed to install.

**Comment by Olive140** [comment]
+ 1 with ubuntu 16.04 64 bits

**Comment by smoetje** [comment]
I can confirm, not working with Ubuntu 16.04 Xenial (LT). I'm newbie on sass, recently shifted to Linux.  Exactly same symptoms liked described above...

**Comment by devdavi** [comment]
Same. Ubuntu 16.04 LTS - 64-bit installs but crashes when attempting to open

**Comment by zaygraveyard** [comment]
I'll try to test it as soon as I can and let you know what I find

**Comment by callmeNewbie** [comment]
try to install like this https://github.com/oklai/koala/wiki/Unable-to-run-Koala-in-Linux

**Comment by zaygraveyard** [comment]
I just installed a fresh Ubuntu 16.04.1 - 64-bit in a VM (VirtualBox)
And then installed `ruby` and the `Koala` version from `koala-app.com`
And then followed the steps in https://github.com/oklai/koala/wiki/Unable-to-run-Koala-in-Linux

And it worked!

**Comment by smoetje** [comment]
I can confirm, the commendation works.
Thank you very much!

**Comment by zaygraveyard** [comment]
@jzhang28 can we closets issue?

**Comment by callmeNewbie** [comment]
yeah close the issues :)
