### ISSUE TITLE
$color: "#c2000e" is not a color for `lighten'

### ISSUE THREAD

**Issue by SamThilmany** [oklai/koala#541]
I use a variable called `$red` in my project which is set to the value of `#c2000e`.

I used the variable in a code snippet like this `background-color: lighten($red,60);` and everything worked well. As the snipped above repeats with different colors for many different divs, I wanted to clean up my code using an `@each` Sass loop.

But when compiling the new code I get an Error: _$color: "#c2000e" is not a color for `lighten'_

Why is that? If the color is okay when using it outside the loop, why isn't it inside the loop?

The color:
`$red: #c2000e;`

The old repetitive code where the color was okay:
```
.alert-danger {
  color: $red;
  background-color: lighten($red,60);
  border-color: lighten($red,55);
  border-left: 3px solid $red;
}
```

The new loop where the same color is not a color for lighten:
```
@each $name, $color, $bg-light, $border-light in (danger, $red, 60, 55),
                                                 (warning, $orange, 35, 30),
                                                 (info, $blue, 60, 55),
                                                 (success, $green, 65, 60){
  .alert-#{$name} {
    color: #{$color};
    background-color: lighten(#{$color}, #{$bg-light});
    border-color: lighten(#{$color}, #{$border-light});
    border-left: 3px solid #{$color};
  }
}
```

Thanks in advance for all help.

**Comment by zaygraveyard** [comment]
The [#{}](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_) operator should not be used in this case.

```scss
@each $name, $color, $bg-light, $border-light in (danger, $red, 60, 55),
                                                 (warning, $orange, 35, 30),
                                                 (info, $blue, 60, 55),
                                                 (success, $green, 65, 60){
  .alert-#{$name} {
    color: #{$color};
    background-color: lighten($color, $bg-light);
    border-color: lighten($color, $border-light);
    border-left: 3px solid #{$color};
  }
}
```

**Comment by SamThilmany** [comment]
You are awesome. Thanks!!

**Comment by pmfgerd** [comment]
Great, thanks!
