### ISSUE TITLE
Less 转换calc()属性错误

### ISSUE THREAD

**Issue by Sihon** [oklai/koala#544]
less中的calc(100% - 30px); 处理成css后会变成calc(70%);

**Comment by mqliutie** [comment]
改为  ~"calc(100% - 30px)"

**Comment by bcawrse** [comment]
I think I'm having this same issue. Less calc() is not working correctly, calc(50% - 80px) results in calc(30%).

**Comment by zaygraveyard** [comment]
Tell Less to ignore calc: http://stackoverflow.com/questions/16323310/how-can-i-instruct-less-to-ignore-math-for-certain-styles (or use the Strict Math option)

**Comment by bcawrse** [comment]
Aha! I just saw this stackoverflow answer and came here to mention it. @zaygraveyard, thanks for responding and beating me to it!
Looks like it's a Less issue and not a Koala one? So this should be closed?
