### ISSUE TITLE
CSS to SASS

### ISSUE THREAD

**Issue by JimKalligas** [oklai/koala#546]
Hi I hope this is the right place to ask. My question is:
I use koala at my work but the compiled css many times get changed by my colleagues. How can the changes apply on my sass? Is there a way with koala or I must write their rewrite their css to sass? Please help me

**Comment by zaygraveyard** [comment]
Sorry I don't think it's possible (I didn't find any program/library that does it).
Your best bet is to generate a diff of the CSS and apply them manually to the SASS.
