### ISSUE TITLE
Error compiling Bourbon

### ISSUE THREAD

**Issue by keizaiweb** [oklai/koala#548]
Hi everyone,
I've an issue with Koala, when I compile a SASS main file where there is an include of the bourbon library I get an error with no message.
In the dev tools, after some tweaks, i get the error SIGTERM. 
The complete JSON returned is:
`Error {killed: true, code: null, signal: "SIGTERM"}`
All the file are on my NAS, nothing is downloaded on the fly.
Any idea?

Thanks

Matteo

**Comment by zaygraveyard** [comment]
Hi @keizaiweb,

Can you give me steps to reproduce this error?

Thank you

**Comment by keizaiweb** [comment]
Hi @zaygraveyard 
I got the error by enabling the top bar of Koala and found it on the developer tools, console.

The problem seems related to the NAS server I used to work on, moving every file on a local disk, it returns no error. Probably the NAS max request rate is really low, I don't know...
Thanks anyway!

Matteo

**Comment by zaygraveyard** [comment]
Thank you for the clarification
Can we close this issue?

**Comment by keizaiweb** [comment]
@zaygraveyard yes, thank you
