### ISSUE TITLE
Custom setting

### ISSUE THREAD

**Issue by csuntitle** [oklai/koala#549]
Dear support team
   Can I import my project without auto compile sass or less file in project folder. I just try to create custom config but it's not effective . My confix like "  "options": {  "autocompile": false } ".

Can you help me for that

Best regards

**Comment by zaygraveyard** [comment]
Hello @csuntitle,
This is a duplicate issue of #367 
You can check [this comment](https://github.com/oklai/koala/issues/367#issuecomment-199269313) on that issue for a workaround.

I hope this helps.
