### ISSUE TITLE
Markdown Compiler

### ISSUE THREAD

**Issue by jawadcode** [oklai/koala#554]
I appreciate how much effort you have put into this but I have found no markdown compilers for the koala app (that work). 
# **`Please Anyone help!!!!`**
Windows Vista compatible please  (^‿^)

**Comment by jawadcode** [comment]
I appreciate how much effort you have put into this but I have found no markdown compilers for the koala app (that work). 
# **`Please Anyone help!!!!`**
Windows Vista compatible please  (^‿^)

**Comment by jawadcode** [comment]
I appreciate how much effort you have put into this but I have found no markdown compilers for the koala app (that work). 
# **`Please Anyone help!!!!`**
Windows Vista compatible please  (^‿^)

**Comment by jawadcode** [comment]
I appreciate how much effort you have put into this but I have found no markdown compilers for the koala app (that work). 
# **`Please Anyone help!!!!`**
Windows Vista compatible please  (^‿^)

**Comment by jawadcode** [comment]
I appreciate how much effort you have put into this but I have found no markdown compilers for the koala app (that work). 
# **`Please Anyone help!!!!`**
Windows Vista compatible please  (^‿^)

**Comment by jawadcode** [comment]
I appreciate how much effort you have put into this but I have found no markdown compilers for the koala app (that work). 
# **`Please Anyone help!!!!`**
Windows Vista compatible please  (^‿^)

**Comment by jawadcode** [comment]
I appreciate how much effort you have put into this but I have found no markdown compilers for the koala app (that work). 
# **`Please Anyone help!!!!`**
Windows Vista compatible please  (^‿^)

**Comment by jawadcode** [comment]
I appreciate how much effort you have put into this but I have found no markdown compilers for the koala app (that work). 
# **`Please Anyone help!!!!`**
Windows Vista compatible please  (^‿^)

**Comment by jawadcode** [comment]
I appreciate how much effort you have put into this but I have found no markdown compilers for the koala app (that work). 
# **`Please Anyone help!!!!`**
Windows Vista compatible please  (^‿^)

**Comment by jawadcode** [comment]
I appreciate how much effort you have put into this but I have found no markdown compilers for the koala app (that work). 
# **`Please Anyone help!!!!`**
Windows Vista compatible please  (^‿^)

**Comment by zaygraveyard** [comment]
@jawadcode There is no need to post the same comment 10 times.
Your request has been noted.
I'm working on updating Koala so that I can add more compilers.
But for now, you need to wait a little.

**Comment by jawadcode** [comment]
Sorry, I just got a bit annoyed because I am wanting to use markdown for my blog posts (on my website) and markdown-js and marked don't get their package.json files detected. I sincerely apologise. 


Sent from Samsung Mobile

-------- Original message --------

**Comment by zaygraveyard** [comment]
@jawadcode It's ok, I understand what you are feeling.
There are lots of markdown flavors out there. Do you have a compiler in mind?

**Comment by jawadcode** [comment]
Any you can recommend for posts? (I just found out what markdown was a few weeks ago).


Sent from Samsung Mobile

-------- Original message --------

**Comment by zaygraveyard** [comment]
You can check [this fantastic css-tricks article](https://css-tricks.com/choosing-right-markdown-parser/) about markdown parsers.
But after looking at the JS options I think I like [remarkable](https://github.com/jonschlinkert/remarkable) the most.

**Comment by jawadcode** [comment]
To make remarkable work do I download the zip and change the extension to
.koala-compiler because with marked and markdown-js it doesn't detect the
package.json file.

**Comment by zaygraveyard** [comment]
No not at all.
I try to create a Koala plugin for that compiler.
The packages that can be added to Koala must be Koala plugins.

**Comment by jawadcode** [comment]
### I figured out how to do it, i use npm to install a markdown compiler written in js and put it on watch at the same time as the jade compiler, but thank you for your help and keep up the great work, lots of people will benefit from your gui compiler.

**Comment by BenRutlandWeb** [comment]
I have created a [koala-markdown](https://github.com/BenRutlandWeb/koala-markdown) compiler. Has the option of minifying the output HTML.

**Comment by jawadcode** [comment]
I downloaded the zip and changed the file extension to .koala-compiler and:
![capture](https://cloud.githubusercontent.com/assets/20072738/26267169/a4ce9bf4-3ce0-11e7-9b94-06f747fd547b.JPG)

**Comment by BenRutlandWeb** [comment]
Download the file in dist directory, then drag and drop into koala interface. I have only tested in win 7 but this should contain everything needed to work. Make sure you're updated to the latest version of koala, currently 2.2.0. Let me know if this doesn't work... I am new to github and to extension dev so forgive me if I made a mistake!
