### ISSUE TITLE
Getting an error on compile

### ISSUE THREAD

**Issue by lkeeney** [oklai/koala#558]
I am completely new to Koala. I generated a simple file called "input.scss" and tried to compile it. This is the error I am getting. I can not figure out how to solve this problem. Can anyone help?

C:\Users\lkeeney\Desktop\test1\scss\input.scss
'sass' is not recognized as an internal or external command,
operable program or batch file.

**Comment by zaygraveyard** [comment]
Hello @lkeeney, I'm sorry to hear that
I just downloaded Koala from http://koala-app.com and installed it in a windows vm
Tried to compile a `.scss` file and it worked.

Can you describe what you tried?

Thank you

**Comment by lkeeney** [comment]
Thank you for your reply.
I found the problem. The check box called "Use The System Sass Compiler" was checked. I unchecked this and it now works.
Do you consult on all different web development problems? I have been looking for someone to help and you are the first one I found.
Do I owe you for this contact?

Sincerely,
Lawrence

**Comment by zaygraveyard** [comment]
> I found the problem. The check box called "Use The System Sass Compiler" was checked. I unchecked this and it now works.

Great 😄

> Do you consult on all different web development problems?

I'm the maintainer of this project (or at least trying to be) since @oklai (the author) is unreachable.
So if you have any problems using Koala, please let me know and I'll try to help.
If you mean in general and not just Koala, then I don't but I'm open for it you find my email address on my github profile page.

> Do I owe you for this contact?

No you don't

Cheers,
Ziad

**Comment by lkeeney** [comment]
Thank you very much. 
After trying a number of different programs, Koala is the program I was looking for.

**Comment by zaygraveyard** [comment]
I'm glad to hear that.
Now can we close this issue? 😄

**Comment by lkeeney** [comment]
Yes. Thank you.
