### ISSUE TITLE
Output CSS with tabs instead of spaces

### ISSUE THREAD

**Issue by dantewebmaster** [oklai/koala#570]
Is there a way to output the final CSS with tab indentation?
How I want my css: 
<pre>
.my-class {
    color: #fff;
}
</pre>

How expandend Koala outputs:
<pre>
.my-class {
  color: #fff;
}
</pre>

**Comment by zaygraveyard** [comment]
What language are you using? LESS or SCSS?

**Comment by dantewebmaster** [comment]
@zaygraveyard SCSS

**Comment by zaygraveyard** [comment]
Unfortunately the [SCSS compiler doesn't support it](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style) 😞

**Comment by dantewebmaster** [comment]
Okay, it's easy to manually select the css file and slect all the css then use ctrl + a > reindent.
Thanks!
