### ISSUE TITLE
Function declaration in If block

### ISSUE THREAD

**Issue by zaros** [oklai/koala#572]
I encountered an issue with this code after it was minified with Koala:

```
var x = 'bar';

function a() {
	console.log('function outside if block');
}

if (x=='foo') {
  function a() {
  	console.log('function inside if block');
  }
}

// should return "function outside if block"
console.log('should return "function outside if block"');
a();
```

Unminified, the code runs correctly. After minified, however, the function inside the If block is triggered instead. 

```
function a(){console.log("function outside if block")}function a(){console.log("function inside if block")}var x="bar";console.log('should return "function outside if block"'),a();
```

It looks like there is no corresponding If statement in the minified code, and the code didn't work as expected.

![console output](https://cloud.githubusercontent.com/assets/738805/23694192/6b1ad180-0413-11e7-953a-0a243410216a.png)

JSFiddle: https://jsfiddle.net/6nvkmz8g/

**Comment by zaygraveyard** [comment]
Koala uses [UglifyJS](https://github.com/mishoo/UglifyJS2) internally, to see the result of UglifyJS you can use [UglifyJS-online](https://skalman.github.io/UglifyJS-online/).

It looks like the option "hoist_funs" is `true` by default and for your case it needs to be `false`.

Unfortunately, at the moment, there is no way to specify options for UglifyJS in Koala :disappointed: 

BTW, I would like to note that, unless this is a thirdparty code or you really need the function to be inside the `if`, it's a bad idea to put functions inside `if` bodies.

**Comment by zaros** [comment]
I think it's arguable if the function should be in the if block or not -- in this case the developer in my team had some good reasons, but it became a bug in our app due to this unexpected behaviour.  Of course now that we know, it's something we would avoid in the future, and we should also test more rigorously post-minify.

But the issue that remains is code which was tested working correctly before minify is then broken after. Is there any warning or safeguards can be triggered in this case?

**Comment by zaros** [comment]
Have updated the JSFiddle with output from [UglifyJS-online](https://skalman.github.io/UglifyJS-online/) as third test. As @zaygraveyard  wrote, if hoist_funs is false, it will work as expected.

**Comment by zaygraveyard** [comment]
> But the issue that remains is code which was tested working correctly before minify is then broken after. Is there any warning or safeguards can be triggered in this case?

Unfortunately UglifyJS does not provide warnings when hoisting functions.
So the only safeguards are your tests.

**Comment by zaros** [comment]
I guess at the end of the day it's going to be a debate whether UglifyJS is correct to hoist functions within if blocks like this.   ¯\_(ツ)_/¯

**Comment by zaygraveyard** [comment]
Closing as this falls outside the domain of Koala
