### ISSUE TITLE
v2.1.0 crash on open [Mac]

### ISSUE THREAD

**Issue by xyboox** [oklai/koala#580]
Hi, on Mac, as soon as I updated to v2.1.0 I can no longer use the app. It crashes on open. ( "Koala quit unexpectedly." ). Any thoughts?

System info:
macOS Sierra 10.12.4

Can I download the prev. version from somewhere?

**Comment by zaygraveyard** [comment]
You can download the previous version from the links [here](https://github.com/oklai/koala/issues/579#issuecomment-297270227).

Can you keep the new version aside for now,
I'll check it out when I get home and I might need you to do some tests, if it's ok with you that is.

Thanks

**Comment by itacode** [comment]
First of all, thank you very much for this very good application.

I have the same crash each time I try to open it.
System info:
macOS Sierra 10.12.4

I rolled back to the previous version.

**Comment by xyboox** [comment]
Sure @zaygraveyard . Let me know. Thanks.

**Comment by themistac** [comment]
Same crash issue here on 10.12.4. I've rolled back in the mean time.

**Comment by localhost8080** [comment]
I get this when opening form commandline, incase it helps:

`LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Koala.app.`

**Comment by digitaloutback** [comment]
Same here..

**Comment by PAULUSfranCIRCUS** [comment]
Same

**Comment by crystalenka** [comment]
Would like to also confirm this on 10.12.4. Rolling back in the meantime. Thanks for all that you do!

**Comment by mikebonds** [comment]
Same issue. Thanks for creating such a great app!

**Comment by zaygraveyard** [comment]
It seams this issue is very similar to an issue in an electron app (electron-userland/electron-packager#323)
Can anyone try to move the old version of the app to the trash (via the Finder) before installing the new version?
Thanks

**Comment by jacobischwartz** [comment]
Same issue. 10.12.4. Trashing then installing did not help.

**Comment by themistac** [comment]
Sorry, no change... still crashing.

**Comment by soxepo** [comment]
I have the same crash each time I try to open it.
10.12.3

**Comment by zzseba78** [comment]
Same here 
macOS Sierra 10.12.4

**Comment by zaygraveyard** [comment]
Can you try [this version](https://drive.google.com/open?id=0B-tHQW4o9rnYLTQ0Rk5CWmxIUmM)?
If it works I'll do a proper release.
Thank you

**Comment by miqalarcia** [comment]
It works for me!

**Comment by themistac** [comment]
Yes! Works for me 👍

**Comment by soxepo** [comment]
Yes! Works 👍
Thanks ))

**Comment by xyboox** [comment]
Is working! Thanks!

**Comment by zaygraveyard** [comment]
Great thanks everyone :smile: 
I'll do a release tonight.

For anyone interested, the source of the problem was the latest version of nwjs (v0.22.0), by reverting to v0.21.6 the error is gone.
I'll file a bug report when I get the time.

**Comment by codesquatch** [comment]
yesssss thank you for the responsiveness and figuring out the bug.

**Comment by zaygraveyard** [comment]
Can anyone verify that [v2.1.2](https://github.com/oklai/koala/releases/tag/v2.1.2) still works?
Thanks

**Comment by xyboox** [comment]
@zaygraveyard works for me on macOS 10.12.4
Anything in particular I should check?

**Comment by zaygraveyard** [comment]
@xyboox Thank you 😄 
I just wanted to make sure that this (the crash) is not happening
because I restored the version of nwjs to the latest one
but I found out that for some weird reason when [`nw-builder`](https://github.com/nwjs-community/nw-builder) downloads it automatically it crashes but not when I download it manually.

**Comment by xyboox** [comment]
Well... it doesn't crash, but there is one issue ( almost sure not related with the crashing one ): after the first compile ( in my case LESS ), the opened app indicator in the dock is turned off and so is the app menu. Only problem with that is that I can no longer close the app ( not even visible in the Force Quit menu ). Only way to close it: restart system. Which is... not quite comfortable.

**Comment by zaygraveyard** [comment]
@xyboox Interesting, I'll look into it tonight.
Can you open open a new issue for this problem?

**Comment by xyboox** [comment]
Done @zaygraveyard

**Comment by zaygraveyard** [comment]
@xyboox Thank you :smiley:

**Comment by zaygraveyard** [comment]
For reference the new issue is #608
