### ISSUE TITLE
Koala 2.1.0 error

### ISSUE THREAD

**Issue by rodenacker** [oklai/koala#582]
I just upgraded to the new Koala 2.1.0 and get the message below when compiling my scss files. Looks like I will have to revert back to Scout... 

![image](https://cloud.githubusercontent.com/assets/2085324/25430837/83fe3462-2a7e-11e7-891d-13343c8e55eb.png)

Franz

**Comment by zaygraveyard** [comment]
Duplicate of #579

**Comment by rodenacker** [comment]
Thanks. When do you expect to have this fixed?
Franz

**Comment by zaygraveyard** [comment]
I'm working on it, so hopefully before tonight
