### ISSUE TITLE
It doesn't not open

### ISSUE THREAD

**Issue by ElYaiko** [oklai/koala#585]
When i wanna open nothing happens just stay opened the process 'koala.exe' but the app doesn't appear and sometimes when it opens, it closes for no reason.

im using windows 10 pro

**Comment by zaygraveyard** [comment]
Thank you for reporting the problem.
I will investigate it tonight.

**Comment by govarthananve** [comment]
Same issue me to face it I also using window 10 pro. Previews version working fine The new version updated then it was not open but background task is running I saw in task manager.

**Comment by govarthananve** [comment]
Working fine for version 2.0.4 for me in windows 10 pro

**Comment by zaygraveyard** [comment]
Can anyone try this [v2.1.2](https://github.com/oklai/koala/releases/tag/v2.1.2)?

**Comment by zaygraveyard** [comment]
I'm assuming this was fixed.
If not please reopen this issue.

**Comment by MakkiAnjum** [comment]
still not opening
