### ISSUE TITLE
Ver 2.1.0 cannot be opened on Mac

### ISSUE THREAD

**Issue by bbrandtlv** [oklai/koala#587]
Hey, just updated to new version (2.1.0) and app cannot be opened.
Deleted and tried again, downloaded again... nothing.
Got back to 2.0.4

**Comment by miqalarcia** [comment]
Same for me!

**Comment by aargenis** [comment]
Same for me

**Comment by puntomaturana** [comment]
Same for me

**Comment by zaygraveyard** [comment]
Is it the same as #580?

**Comment by codesquatch** [comment]
Same

**Comment by KingKarrow** [comment]
@zaygraveyard Yep. I'm seeing it too.

**Comment by zaygraveyard** [comment]
Duplicate of #580
