### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by GuillermoJ** [oklai/koala#588]
![whatsapp image 2017-04-26 at 12 21 18 pm](https://cloud.githubusercontent.com/assets/21283478/25446195/1d009a1c-2a87-11e7-9f99-bd96aaa1861b.jpeg)
![whatsapp image 2017-04-26 at 12 22 38 pm](https://cloud.githubusercontent.com/assets/21283478/25446196/1d06944e-2a87-11e7-9d07-30aaf31fff07.jpeg)

**Comment by zaygraveyard** [comment]
Thank you for reporting, I'll fix it ASAP

**Comment by BRichardson2993** [comment]
Same here:

**Comment by BRichardson2993** [comment]
![koalaerror](https://cloud.githubusercontent.com/assets/13844631/25449959/098c0db2-2a83-11e7-99a0-9a4bbf2f6d3b.PNG)

**Comment by xMrKrisx** [comment]
Since the update that was released yesterday, I'm not able to set any files no more. Kinda shit since im in aa big project and I cant really work any further now....

![bugerror](https://cloud.githubusercontent.com/assets/25393126/25474513/c0c69122-2b33-11e7-96ff-f559bf697dff.png)

**Comment by zaygraveyard** [comment]
@xMrKrisx the issue you are experiencing is the one refereed to by #579.

Sorry for the inconvenience, I fixed this bug and will do a release tonight.
In the mean time anyone having this problem can downgrade back to [v2.0.4](https://github.com/oklai/koala/releases/tag/v2.0.4).
