### ISSUE TITLE
Error: The system cannot find the path specified

### ISSUE THREAD

**Issue by UFBin** [oklai/koala#597]
When I tried to compile my Sass files I got the error "The system cannot find the path specified". Version 2.0.4 does not have this issue. 

Windows 10 x64
Koala 2.1.1

![image 2](https://cloud.githubusercontent.com/assets/13383128/25520038/f0327602-2c2c-11e7-8c88-5a45406308fe.png)

**Comment by Devidelf** [comment]
Same issue

Windows 10 x64
Koala 2.1.1

**Comment by zaygraveyard** [comment]
Merged in #598
