### ISSUE TITLE
Koala ERROR

### ISSUE THREAD

**Issue by edudix** [oklai/koala#599]
Hi, Im pretty new in using this tool. I have installed it, and initially and when compiling Im gettig the following issue. Does anyone now how ro solve it?
BR

![koalaerrors](https://cloud.githubusercontent.com/assets/26487838/25532591/26c96850-2c2e-11e7-8ed2-eb27c093de08.jpeg)
sue.

**Comment by zaygraveyard** [comment]
Hello @edudix, this issue is the same as #579
And normally it was fixed in the version 2.1.1

**Comment by edudix** [comment]
Yes thanks!
