### ISSUE TITLE
Uncaught Exception when setting CSS to Auto Compile

### ISSUE THREAD

**Issue by brubie** [oklai/koala#602]
I don't get this issue when setting SCSS to Auto Compile, but only when it's CSS.

First it shows this error: 
![image](https://cloud.githubusercontent.com/assets/10237830/25549382/523d13cc-2c26-11e7-9b9f-cf46baf9b876.png)

Then this error:
![image](https://cloud.githubusercontent.com/assets/10237830/25549394/5c9a7a9e-2c26-11e7-85ca-2f39bed0f76e.png)

Even if I uncheck the Auto Compile option, I continue to get this error until I quit and restart the app. 

I'm on Mac OS 10.12.4

**Comment by zaygraveyard** [comment]
Which version of Koala are you using?

**Comment by zaygraveyard** [comment]
This issue should normally be fixed in version 2.1.1
If you are experiencing this issue in that version please reopen this issue.

**Comment by brubie** [comment]
This was experienced with version 2.1.1 as well as 2.1.2. The error seems to occur when trying to compile a CSS file into a minified CSS. If I uncheck all the auto-compile options, the SCSS compiles but the CSS does not.

**Comment by zaygraveyard** [comment]
Sorry I had miss analyzed this issue, but the good news is that it has been fixed in v2.1.3 (soon to be released)
