### ISSUE TITLE
system cannot find the path specified

### ISSUE THREAD

**Issue by leocirculo** [oklai/koala#606]
I have downloaded and installed the latest version of Koala. 

First I was having a bunch of errors and the application frozed everytime I tried to compile, so I made a clean install and erased all of my current projects.

When I added a new project I get this error every time I try to compile

18:03:26
El sistema no puede encontrar la ruta especificada.

Wich is spanish for "the system can't find the path specified".

Any suggestions?

EDIT: I'm using Windows

![image](https://cloud.githubusercontent.com/assets/19593762/25594897/f9cf036a-2e98-11e7-9b64-50f19e62c2f0.png)

**Comment by zaygraveyard** [comment]
Duplicate of #598
