### ISSUE TITLE
v2.1.2 Css file compile error and uncaughtException

### ISSUE THREAD

**Issue by Her-ero** [oklai/koala#607]
sys: win7 x64 sp1

![error](http://i1.piimg.com/1949/39878108b6347c44.png)
![uncaughtException](http://i1.piimg.com/1949/5a53b18c6cb791c6.png)

Thanks.

**Comment by zaygraveyard** [comment]
Thank you for reporting this bug.

**Comment by zaygraveyard** [comment]
I'll do a release tonight.
But for now a workaround is to apply 60b001903048a00dd46bf12dbdf6bee937046ddc to `C:\Program Files (x86)\Koala\app\scripts\compilers\CssCompiler.js`
