### ISSUE TITLE
koala.exe gone / unaccessible

### ISSUE THREAD

**Issue by 45grad** [oklai/koala#610]
Just installed 2.1.3.; Now there is no application file to execute in the install dir. While trying to reinstall there is a prompt that koala.exe cannot be accessed, although there is no running process (neither koala nor nwjs). No luck after uninstall and reinstall after reboot: still no executable.
OS is Windows 10 Pro.

Anyone with similar problems?

**Comment by lifenstein** [comment]
@45grad I have the same issue, just created #623. How did you fix this?

**Comment by lifenstein** [comment]
Nevermind, found #617, which seems to be causing this.
