### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by solarcellsky** [oklai/koala#611]
![image](https://cloud.githubusercontent.com/assets/546897/25693192/87a7fdd4-30da-11e7-98dd-94cbdaf71d15.png)
突然报这个错是咋回事，版本 2.1.3

**Comment by cyberwani** [comment]
I am facing same issue.

**Comment by CrixuAMG** [comment]
Is there any timeframe on when this issue is fixed? I love the app, but I cannot work with it while this error is occurring.

**Comment by zaygraveyard** [comment]
I'll fix it tonight or tomorrow
So hang tight @CrixuAMG :wink:

**Comment by CrixuAMG** [comment]
Thanks @zaygraveyard! Looking forward to the update! ^^

**Comment by zaygraveyard** [comment]
Fixed in the new version [v2.1.4](https://github.com/oklai/koala/releases/tag/v2.1.4)
