### ISSUE TITLE
css.replace is not a function

### ISSUE THREAD

**Issue by CrixuAMG** [oklai/koala#613]
Using the latest version on Windows 10 64 bit.

Whenever I open the app, it automatically causes this error (auto compile is enabled for all files) and ceases to function from then on.
It started happening after I updated to the latest version.

I have no issues trying to compile the same files on a different system, using an older version.

**Comment by zaygraveyard** [comment]
Duplicate of #611

**Comment by CrixuAMG** [comment]
How is this a duplicate? It's a different issue.

**Comment by zaygraveyard** [comment]
Sorry you are right it not the same issue :sweat_smile: 
Which version are you using?

**Comment by CrixuAMG** [comment]
Just updated to the newest version (2.1.3), and I don't have the issue anymore, but now I get "Cannot read property length of undefined" when compiling css.

**Comment by zaygraveyard** [comment]
Great, new issue is #611
