### ISSUE TITLE
koala2.1.3安装，运行报错

### ISSUE THREAD

**Issue by mhxy13867806343** [oklai/koala#616]
我在github官方找到koala最新的版本，安装完了之后，金山杀毒软件就报了一个病毒出来，名字叫win32trojan.generic_a.a ，不能使用新版本，是否能处理下

**Comment by zaygraveyard** [comment]
Does [NW.js](https://dl.nwjs.io/v0.22.1/nwjs-v0.22.1-win-ia32.zip) have a trojan?

**Comment by mhxy13867806343** [comment]
nw.js不清楚是否是病毒，已经解决了，能够使用了，我用win7 管理员方式安装的，就可以了

**Comment by zaygraveyard** [comment]
Is this still valid for version [v2.1.4](https://github.com/oklai/koala/releases/tag/v2.1.4)?

**Comment by mhxy13867806343** [comment]
忽略它吧，实际上无这个文件，属于误报。 作者在微博里面回复我的

**Comment by zaygraveyard** [comment]
ok thanks
