### ISSUE TITLE
SASS Compile

### ISSUE THREAD

**Issue by ArizonaInkStudios** [oklai/koala#619]
When I attempt to compile scss to css in version 2.1.3, it does so successfully, BUT the file does not update or change. I have tried recreating the file. I even deleted the contents of both the source and the destination and nothing changes; the destination is not getting written. Even if I change an option under the scss options, Expanded->Compressed, I get a successful message, but the output file does not change.

The last version I was using was 2.0.4, so I am unaware which version after 2.0.4 the issue started appearing.

**Comment by zaygraveyard** [comment]
If you manually compile (by clicking on the compile button) the sass file, does the output css update?

**Comment by ArizonaInkStudios** [comment]
Unfortunately no.

I tried compiling via right-click.
I tried compiling via the compile button.
I even deleted all the contents of the output file and compiled with no luck.

Are there logs I can look at to help out better figure out what is going on?

I am on Windows 10.

**Comment by hworm4** [comment]
I had the same issue that happened when first time added files but bug disappear after close and reopen app

**Comment by ArizonaInkStudios** [comment]
I have tried version 2.1.4 and I am seeing the same issue.

I am using a recently already used project that I was using on 2.0.4.

I had the idea of removing the files and re-adding them. I do not want to do this for all my files in the project, but I will if I have to. I removed one just for a test and after adding it back it still will not output.

I also now know that the output issue is only occurring with scss files. I tried this with my js files in the project and they work just fine.

I added a very simple scss file with only one statement and attempted to compile and it errored.

I should mention I did this from an install as an "upgrade". In other words, I installed 2.1.4 right over 2.0.4 without uninstalling. Note, when I go back to 2.0.4, I do not uninstall either and it works fine.

After a clean uninstall of 2.1.4 and ensuring all previous versions were gone and uninstalled as well. After doing a clean install I still get this behavior. It says it compiles successfully but nothing happens in the output file.

What else can I try to help diagnose this issue?

**Comment by zaygraveyard** [comment]
Thank you for the detailed analysis.
Is the "Compass Mode" checked on the scss file?

**Comment by ArizonaInkStudios** [comment]
No. Only auto compile and prefix are checked.

**Comment by zaygraveyard** [comment]
Try this:
1. Go to the install dir of koala
2. Apply [this commit](https://github.com/oklai/koala/pull/618/commits/b85becd407fd2a4819fa19dd505590556f7c5d39) (manually)

**Comment by zaygraveyard** [comment]
Forgot to mention you also need to restart Koala after the change (quit completely then open it)

**Comment by ArizonaInkStudios** [comment]
I will do so and let you know!

**Comment by ArizonaInkStudios** [comment]
Unfortunately that did not change the behavior.

**Comment by zaygraveyard** [comment]
1. In the same file you modified recently (`SassCompiler.js`), add `alert(command);` before the `exec()` call (line 150)
2. Restart Koala
3. Try to compile the SCSS file
4. You will see an alert popup, copy it's contents
5. Open `cmd.exe` (the terminal on windows)
6. Paste the contents of the alert from earlier (to paste on `cmd.exe` right-click in and select "Paste")

Let me know what happens

**Comment by ArizonaInkStudios** [comment]
Ok so this is the most bizarre crazy software bug ever! I have done all of those things you suggested and first off the alert did not do anything. I am not really sure why, but true story nonetheless.

As to the weird part of this. I received some windows updates recently and my machine rebooted. Guess what? Version 2.1.4 works without issue. Without the added force argument. I do not know why. I do not understand why a reboot would have helped, but alas it did.

Thank you for all your time and for this GREAT awesome software. I am sorry for making you scratch your head over a bug that was not a bug. But good news, nothing to fix!? LOL

**Comment by zaygraveyard** [comment]
Fantastic :smile: 
I guess this will remain a mystery forever :wink:.

**Comment by ArizonaInkStudios** [comment]
I guess reboot really is the answer? :laughing:
