### ISSUE TITLE
Notifications are interrupting work flow

### ISSUE THREAD

**Issue by Ngranger** [oklai/koala#621]
I've been using Microsoft's VS Code (Auto Save enabled) with Koala and your program has been reacting to every little change I make in the SCSS files, causing window focus to suddenly shift to the notification which impedes my attempts to quickly code.  I'm hoping you will add an option or options to Koala to allow users to either not have notifications displayed at all or perhaps letting an user to set a compilation interval of their choice.

**Comment by wzs28150** [comment]
I have the same problem,window focus to suddenly shift to the notification which impedes my attempts to quickly code.
