### ISSUE TITLE
Add support for ES6+

### ISSUE THREAD

**Issue by YOU-TIME** [oklai/koala#622]
File download always fails, can add a new download address.
Can increase the ES6 syntax recognition, to avoid errors

**Comment by zaygraveyard** [comment]
> File download always fails, can add a new download address.

Which link are you referring to?

> Can increase the ES6 syntax recognition, to avoid errors

Koala uses [UglifyJS2](https://github.com/mishoo/UglifyJS2) so when uglify adds support for ES6 Koala will automatically have it.

**Comment by shikkaba** [comment]
> Koala uses UglifyJS2 so when uglify adds support for ES6 Koala will automatically have it.

It's in the dev branch so it's coming! Apparently?

> Release versions of uglify-js only support ECMAScript 5 (ES5). If you wish to minify ES2015+ (ES6+) code then please use the harmony development branch.
