### ISSUE TITLE
Installer fails to create Koala.exe

### ISSUE THREAD

**Issue by lifenstein** [oklai/koala#623]
Koala version 2.1.4, Windows 7 Enterprise, 64 bit.

After choosing install directory (I left it at default, `C:\Program Files (x86)\Koala`) and clicking next, I get the warning:
```
---------------------------
Koala Setup
---------------------------
Error opening file for writing: 

C:\Program Files (x86)\Koala\Koala.exe

Click Abort to stop the installation,
Retry to try again, or
Ignore to skip this file.
---------------------------
Abort   Retry   Ignore   
---------------------------
```
If I choose "Ignore", all the other files are written to the directory, but not Koala.exe.

I tried with the previous version (2.1.3), and the error remained. Right-clicking and choosing "Run as administrator" has no effect.

**Comment by lifenstein** [comment]
BitDefender (free edition) thinks Koala.exe has Trojan, so this is related to #617.

**Comment by zaygraveyard** [comment]
Still an issue with v2.2.0?

**Comment by koosabang** [comment]
today 15/05/17 avast(free edition) thinks koala.exe has trojan. I download  V2.2.0.

**Comment by zaygraveyard** [comment]
@koosabang does it say which one?

**Comment by lucker-lv** [comment]
yes, it's many days, it cann't to download. hope to solve!

**Comment by lifenstein** [comment]
I don't have this issue with 2.2.0. It may be the case that AV programs have blacklisted the paths and URLs, and it might take a while for them to be taken off.

**Comment by zaygraveyard** [comment]
Thanks @lifenstein, I'm closing this for now
