### ISSUE TITLE
sass文件包含中文时编译出错，以及linux安装问题

### ISSUE THREAD

**Issue by fengcms** [oklai/koala#624]
sass文件在包含中文时会编译出错，我知道给文件`/rubygems/gems/sass-3.4.23/lib/sass/engine.rb`末尾插入
```#
Encoding.default_external = Encoding.find('utf-8')
```
可以解决问题，但是每次升级的时候都需要重新编辑一下。建议直接编辑进去，避免这个问题。

另外，建议将koala加入linux的各个仓库，比如 arch的pacman和ubuntu的apt仓库，这样可以用命令行一键安装。

我在arch中进行手工安装的时候，出现一个文件和系统版本不一致的问题，每次在arch上安装都有一种想要自杀的感觉，得处理好久。希望在linux上的体验可以更好一些。

**Comment by zaygraveyard** [comment]
Did you try to add `@charset "UTF-8";` at the beginning of the file?
I refuse to edit the sass gem, if you think this is a bug in sass you should file an issue on their project.

I am aware that Koala is not Linux friendly and this will hopefully change one I replace NW.js with electron.
I might try create an AUR package for Koala, but I have never don't it before so don't hold your breath.

**Comment by fengcms** [comment]
Ok, I know what you mean, Think U

**Comment by zaygraveyard** [comment]
Let me know if adding `@charset` fixed the problem.
Thanks

**Comment by fengcms** [comment]
`@charset` It's work , but need to add to each file

**Comment by zaygraveyard** [comment]
Fantastic :smile:

**Comment by zaygraveyard** [comment]
See #625 and #626 for progress on linux packages
