### ISSUE TITLE
How can I use koala to compile sass into css file encoding with "utf-8"

### ISSUE THREAD

**Issue by JerryWenlong** [oklai/koala#63]
How can I use koala to compile sass into css file encoding with "utf-8"?
Or has any other way to do this?  
Thanks.

**Comment by waclawjacek** [comment]
But doesn't this mean the default encoding isn't utf-8?

P.S. Confirmed, `@charset "utf-8";` fixes it.

**Comment by Nantonos** [comment]
The default should be utf-8 in any case. And if not, there should be an option to set the default in koala setup.
I used Koala to do .scss to css conversion, and it interpreted the bytes as Latin-1 (and then output those as UTF-8 characters) so a checkmark (tick) became three random characters. Had to fix manually.
Certainly, @charset should be parsed. But the default should still be UTF-8, even in the absence of a Byte Order Mark.

**Comment by ve3** [comment]
Koala can't compile non utf-8 characters.
@charset "utf-8"; doesn't work.
In Sass it needs this parameter `-E "UTF-8" to make it compile correctly. And in Koala? add optional sass parameters maybe? but it don't have an option to do?

**Comment by unbolt** [comment]
@ve3 Did you come up with a solution to this? Having the same problem currently. I have installed SASS externally and tried using that, but can't pass additional parameters to it.

Have tried setting the charset to UTF-8, but it still doesn't work, using the internal or command line compiler.

**Comment by AJayHubs** [comment]
Any update on this, can't seem to get it to work.

**Comment by jamesbondo** [comment]
brilliant
