### ISSUE TITLE
Koala won't start, returns 0xc000007b

### ISSUE THREAD

**Issue by boyum** [oklai/koala#630]
**Koala version 2.2.0**

**Bug report**

I just updated Koala to v2.2.0 on my 64 bit Win10 env. Now the program won't start, and only returns `0xc000007b`.

**Comment by zaygraveyard** [comment]
Thanks for reporting, I'll check it out tonight

**Comment by AlexKlaus80** [comment]
I get the same error. (Windows10.0.15063, x64)
My machine had never ran Koala before so I..
1. Installed Ruby 2.3.3 (x64) (:not sure if required but I installed it anyways) and Restart Windows
2. Run KoalaSetup.exe
3. Run Koala.exe
and I also got 0xc000007b

**Comment by T-hY** [comment]
Same for me, i updated it without issues at work on a Windows 7 64bits system, but at home on Windows 10 64bits it won't start and return this error.

**Comment by zaygraveyard** [comment]
@AlexKlaus80 ruby is not required, Koala has it's own copy of ruby bundled with it.

**Comment by drlogics** [comment]
Same problem with me, error 0xc000007b. (Windows 10 Pro, 64-bit). Hope you can correct it soon.

**Comment by zaygraveyard** [comment]
It seams that there was a problem with the binary I used to create Koala.
I recreated the Koala and now it should work normally.
I'm uploading the new KoalaSetup.exe
I'll let you know when it's done.

**Comment by BeRambo** [comment]
Same error

**Comment by zaygraveyard** [comment]
All done, can anyone try it?

**Comment by AlexKlaus80** [comment]
It worked! Thanks for quick fix!

**Comment by drlogics** [comment]
Thanks, Man. It's a success for me, too. Kudos for the quick fix! Thumbs up...

**Comment by T-hY** [comment]
Working for me too.
Thanks a lot for that !

**Comment by zaygraveyard** [comment]
Great, thank you guys :smile:
