### ISSUE TITLE
一次崩溃的体验

### ISSUE THREAD

**Issue by cipchk** [oklai/koala#633]
我们有个angular项目，每个组件都是一个独立的文件夹，都有相应对的 xxx.component.scss，然后不小心把根目录拉进 koala 里面，最后上百个组件下面，每一个文件夹都帮我生成了：

xxx.component.css
xxx.component.css.map

不说了，GIT的变更99+；我一个个删除去了！

**Comment by zaygraveyard** [comment]
Sorry this might be because of the translation but I didn't understand the problem you are facing.

**Comment by cipchk** [comment]
HAHA -_-，我一直以为是中国人。
