### ISSUE TITLE
File outputs...

### ISSUE THREAD

**Issue by labradorconnect** [oklai/koala#643]
2.2.0

Once I compile a LESS file, where does the CSS file get saved to in Windows? Thanks!

**Comment by zaygraveyard** [comment]
To see where output is saved you can right-click the LESS item in Koala and select "Open output folder", to change it you can select "Set output path" or click on the icon shown in the figure (red arrow)
And the output path is shown is highlighted in the figure by the green underline.

![screen shot 2017-05-25 at 16 13 31](https://cloud.githubusercontent.com/assets/603764/26453839/6da1616e-4165-11e7-81be-f8151283756a.png)

**Comment by labradorconnect** [comment]
Thank you. I see that but the output is resulting in empty css files.
Please see attached.

-Brian Riback
P: (201) 258-9171
E: briback@labradorconnect.com


   -
      - www.linkedin.com/in/brianriback
   - The contents of this e-mail message and any attachments are
   confidential and are intended solely for addressee. The information may
   also be legally privileged. This transmission is sent in trust, for the
   sole purpose of delivery to the intended recipient. If you have received
   this transmission in error, any use, reproduction or dissemination of this
   transmission is strictly prohibited. If you are not the intended recipient,
   please immediately notify the sender by reply e-mail or phone and delete
   this message and its attachments, if any.
   - Any form of reproduction, dissemination, copying, disclosure,
   modification, distribution or publication of this material is strictly
   prohibited.

**Comment by zaygraveyard** [comment]
@labradorconnect There is nothing attached 😟

**Comment by labradorconnect** [comment]
That's because I replied via email. I guess they got stripped. Here they are. Thanks!
[variables.zip](https://github.com/oklai/koala/files/1029327/variables.zip)

**Comment by zaygraveyard** [comment]
This is the correct output, `variables.less` contains only variable definitions and comments which don't generate any CSS.
You can try to compile LESS into CSS independently from Koala using the online tool [less2css](http://less2css.org).

**Comment by labradorconnect** [comment]
Thank you so much! This REALLY helps.

-Brian Riback
P: (201) 258-9171
E: briback@labradorconnect.com


   -
      - www.linkedin.com/in/brianriback
   - The contents of this e-mail message and any attachments are
   confidential and are intended solely for addressee. The information may
   also be legally privileged. This transmission is sent in trust, for the
   sole purpose of delivery to the intended recipient. If you have received
   this transmission in error, any use, reproduction or dissemination of this
   transmission is strictly prohibited. If you are not the intended recipient,
   please immediately notify the sender by reply e-mail or phone and delete
   this message and its attachments, if any.
   - Any form of reproduction, dissemination, copying, disclosure,
   modification, distribution or publication of this material is strictly
   prohibited.

**Comment by labradorconnect** [comment]
I realize this question falls outside of Koala but I'd really appreciate some help, if possible. I used the less2css and the result came out blank. Any idea why?

![image](https://cloud.githubusercontent.com/assets/16386942/26460250/12f8afa6-4147-11e7-8ec6-863beafcec3b.png)

**Comment by zaygraveyard** [comment]
What are you expecting to get?

**Comment by zaygraveyard** [comment]
Any updates?
