### ISSUE TITLE
Auto prefix does not work

### ISSUE THREAD

**Issue by ThomasWBauer** [oklai/koala#644]
Koala version 2.2
Windows 7 64bit

I am using "display:flex" and "transition". In options I have activated "Autoprefix" for SASS. But in the css file there are no prefix for both.

**Comment by zaygraveyard** [comment]
I can't reproduce it!
Can you post a snippet?

**Comment by ThomasWBauer** [comment]
![2017-05-28 19_58_27-koala - a cool tool for web developers](https://cloud.githubusercontent.com/assets/28964007/26530977/66e48c02-43e0-11e7-9931-6fcc44fa974e.png)

**extract scss file**
![2017-05-28 19_59_42-topstyle lite 3 10 c__www_kunden_lederer_sass_main scss](https://cloud.githubusercontent.com/assets/28964007/26530984/7a76d748-43e0-11e7-8c1d-d00b766ece1a.png)

**extract css file**
![2017-05-28 20_02_20-topstyle lite 3 10 c__www_kunden_lederer_stylesheets_main css](https://cloud.githubusercontent.com/assets/28964007/26530997/a92970d2-43e0-11e7-9217-2a4ae2c3dafa.png)

**Comment by zaygraveyard** [comment]
Can you try selecting the file in Koala and in the side menu verifying that the "Autoprefix" is checked?
The ones in the picture is the setting that are the default settings that get overwritten by file settings

**Comment by ThomasWBauer** [comment]
![2017-05-29 06_54_41-koala - a cool tool for web developers](https://cloud.githubusercontent.com/assets/28964007/26536968/c0312e86-443b-11e7-831e-ad2b018edcf4.png)

**Comment by ThomasWBauer** [comment]
The problem has been solved by itself. I do not understand the background. The compilation by SASS was done in an automatic created folder "stylesheets". Now - since about one hour - the compilation goes to a folder "css" - and here it works. I haven't changed any directory names. I only "played" with the options for output style.
Nevertheless: I am happy, that it works. May somebody knows the details behind of the both directories and can explain it.
