### ISSUE TITLE
"Entry Point Not Found" after updating to current 2.2.0 version

### ISSUE THREAD

**Issue by phoutekier** [oklai/koala#649]
**Koala version 2.2.0**

After updating to the current version from 2.0.4 (originally installed ~1yr ago), Koala will no longer launch. The error message is "The procedure entry point ReleaseSRWLockExclusive could not be located in the dynamic link library KERNEL32.dll". This is on an older Windows Server 2003r2 machine. 

![koala](https://cloud.githubusercontent.com/assets/29231894/26834372/2570b466-4aa3-11e7-94bf-7aeb0fd640e2.PNG)

**Comment by zaygraveyard** [comment]
Can you try running NW.js to see if it works? (you can get it from [here](https://nwjs.io/downloads/), use the normal version)
Thanks

**Comment by zaygraveyard** [comment]
In the mean time you can revert back to the 2.0.4 version.
Download links can be found in [#579 (comment)](https://github.com/oklai/koala/issues/579#issuecomment-297270227).

**Comment by phoutekier** [comment]
No, trying to run nw.exe from that download gets the exact same error. The procedure entry point could not be located.

**Comment by zaygraveyard** [comment]
I afraid this means that the new version of NW.js (which Koala uses) no longer support Windows Server 2003r2 😞

**Comment by phoutekier** [comment]
We’re updating that server next quarter so I’ll just have to hold out on the update for a bit. Thanks for your help.
