### ISSUE TITLE
Unable to drag folder into Koala app

### ISSUE THREAD

**Issue by aranhaag** [oklai/koala#651]
**Koala version** 2.2.0

**Bug report or feature request?**

While dragging project folder to Koala app window, I get the error as per attached file.  Even at the time of linking partial files also I get the error.
Please let me know how to rectify.  I want to prepare a tutorial video on Koala. Hence, please help me out in installing Koala without error.

Regards and thanks

![drag-error](https://user-images.githubusercontent.com/15772126/26915589-5f32ad6a-4c44-11e7-90c0-bc0d68c8ec2b.JPG)
![koala_error-partial file](https://user-images.githubusercontent.com/15772126/26915601-663d7806-4c44-11e7-8806-8490573f0a11.JPG)

**Comment by zaygraveyard** [comment]
There is no version `2.2.2` do you mean `2.2.0`?

**Comment by zaygraveyard** [comment]
Does the file `%USERPROFILE%/.koala/imports.json` exist? and if so what's it's contents?
Thanks

**Comment by aranhaag** [comment]
Hello Sir,file %USERPROFILE%/.koala/imports.json does not exist in c:\programmes files(x86) folder. 
RegardsAranhaag 

    On Thursday, 8 June 2017 1:36 PM, Ziad El Khoury Hanna <notifications@github.com> wrote:
 

 Does the file %USERPROFILE%/.koala/imports.json exist? and if so what's it's contents?
Thanks—

**Comment by aranhaag** [comment]
Sorry. Yes it is 2.2.0.  I am attaching the imports.json file. Please have a look and let me know.
Regards
Aranhaag 

    On Thursday, 8 June 2017 1:29 PM, Ziad El Khoury Hanna <notifications@github.com> wrote:
 

 There is no version 2.2.2 do you mean 2.2.0?—

**Comment by zaygraveyard** [comment]
Sorry, Github doesn't accept email attachments!

**Comment by aranhaag** [comment]
I find that it contains all zeros like 0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000 . Is it correct?
Regards
Aranhaag 

    On Thursday, 8 June 2017 3:26 PM, Ziad El Khoury Hanna <notifications@github.com> wrote:
 

 Sorry, Github doesn't accept email attachments!—

**Comment by zaygraveyard** [comment]
No its not.
It should be JSON!
Can you quit Koala, delete the file, and restart Koala to see if the problem is fixed?

**Comment by aranhaag** [comment]
Yes my friend.  I deleted the file. Re-installed koala and it is working fine now. Tks a lot !
Regards
Aranhaag 

    On Thursday, 8 June 2017 3:38 PM, Ziad El Khoury Hanna <notifications@github.com> wrote:
 

 No its not.
It should be JSON!
Can you quit Koala, delete the file, and restart Koala to see if the problem is fixed?—

**Comment by zaygraveyard** [comment]
Great 😄 
Let us know when you finish your tutorial 😄
