### ISSUE TITLE
help! update to koalo 2.2 Compiler Error

### ISSUE THREAD

**Issue by zxlp1023** [oklai/koala#657]
**Koala version** 2.2

**Bug report or feature request?**

![image](https://user-images.githubusercontent.com/18332379/27250723-8942551c-5368-11e7-8274-5d70f201fc4c.png)
![image](https://user-images.githubusercontent.com/18332379/27250725-94f031e0-5368-11e7-9080-f89614d42dd9.png)
![image](https://user-images.githubusercontent.com/18332379/27250727-9bd293ea-5368-11e7-819a-82cba7fff74a.png)
![image](https://user-images.githubusercontent.com/18332379/27250729-a0c0fc20-5368-11e7-9a0a-47606caa9b98.png)
![image](https://user-images.githubusercontent.com/18332379/27250730-a6c13dba-5368-11e7-82ad-ea795e05bb15.png)
![image](https://user-images.githubusercontent.com/18332379/27250732-ab801b5a-5368-11e7-8984-2595bb611f2c.png)
![image](https://user-images.githubusercontent.com/18332379/27250734-bda118b6-5368-11e7-9f16-788045dc604c.png)

**Comment by zaygraveyard** [comment]
Merging in #639 
Please can you try to reinstall Koala?
