### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by brubie** [oklai/koala#661]
**Koala version 2.2.0**
**Mac version 10.12.5**

**Bug report**

Receive the following error whenever compiling a SCSS file. If compiling multiple files then it throws an error for each file. 

```---uncaughtException---
TypeError: Cannot read property '...css/_style.scss' of null
    at /Applications/Koala.app/Contents/Resources/app.nw/app/scripts/fileWatcher.js:133:30
    at Array.forEach (native)
    at Object.exports.addImports (/Applications/Koala.app/Contents/Resources/app.nw/app/scripts/fileWatcher.js:132:13)
    at getOrWatchStyleImports (/Applications/Koala.app/Contents/Resources/app.nw/app/scripts/compilers/common.js:63:21)
    at Object.exports.watchImports (/Applications/Koala.app/Contents/Resources/app.nw/app/scripts/compilers/common.js:79:5)
    at /Applications/Koala.app/Contents/Resources/app.nw/app/scripts/compilers/SassCompiler.js:160:20
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
```

Dismissing the alert still compiles the file, but I have to close the alert window for every file to be compiled. This becomes a huge nuisance when updating a base SCSS file that's imported into 50+ files.

**Comment by zaygraveyard** [comment]
Can you try to:
1. Quit Koala
2. Delete `~/Library/Application Support/Koala/UserData/imports.json`
3. Lunch Koala

**Comment by zaygraveyard** [comment]
@brubie any updates?

**Comment by brubie** [comment]
That resolved the issue

**Comment by zaygraveyard** [comment]
Great, thanks

**Comment by dudupavani** [comment]
Don't exist " Library/Application Support/Koala/UserData/imports.json " this paste or file on mac.

**Comment by devonatdomandtom** [comment]
@dudupavani you may have to escape the space in "Application\ Support".

``rm Library/Application\ Support/Koala/UserData/imports.json``

**Comment by jfall** [comment]
I was able to delete that file on the mac, but am still getting the error:

---uncaughtException---
TypeError: Cannot read property '_custom-variables.scss' of null

**Comment by tadeugarcia** [comment]
> Can you try to:
> 
> 1. Quit Koala
> 2. Delete `~/Library/Application Support/Koala/UserData/imports.json`
> 3. Lunch Koala

It worked for me too, thank you so much!
