### ISSUE TITLE
How to install on Linux?

### ISSUE THREAD

**Issue by fredw** [oklai/koala#67]
Goodnight,

You could complement the documentation installation in Linux? You could complement the documentation installation in Linux?
Excuse my ignorance, but I have not figured out how to install it. I'm no Linux expert.
How should I proceed?

Thank you!

**Comment by jose-rodriguez** [comment]
Steps to install Koala in Linux:

tar xvf koala_2.0.4_amd64.tar.gz
su -c "mv koala /opt"
su -c "ln -sv libudev.so.1 /usr/lib64/libudev.so.0"
.koala/koala

**Comment by ddeveloperr** [comment]
Hi guys, 
Previous script required a root password then was back to me authentication error in terminal, even though I typed correct password 100% , and finally it works 100% with sudo: 
   
tar xvf koala_2.0.4_amd64.tar.gz
sudo -c "mv koala /opt"
sudo -c "ln -sv libudev.so.1 /usr/lib64/libudev.so.0"
.koala/koala

The root account is locked by default, so you can't use "su" to switch to root.  Use sudo to run a command with root privileges!

**Comment by Muco-Tresor** [comment]
hi guy please help i'm on ubuntu i install koala but it refuses to run

**Comment by zaygraveyard** [comment]
@Muco-Tresor Can you give us more details? Like how did you install it, and what's the error.
Thanks

**Comment by danielogin** [comment]
A mi me resulto esto en UBUNTU, en 16.04 dicen que suele dar problemas y la aplicación no abre después de instalada. La solución es esta:

32bit: $ cd /lib/i386-linux-gnu/ or $cd /usr/lib/

64bit: $ cd /lib/x86_64-linux-gnu/ or $cd /usr/lib64/

$ sudo ln -s libudev.so.1 libudev.so.0

Si el archivo libudev no está en el directorio linux-gnu o no lo encuentra instala libudev0:
*es realizar por lo que entiendo un enlace simbolico a la nueva version de la libreria
