### ISSUE TITLE
Deleting Files From Hardrive

### ISSUE THREAD

**Issue by StefJohns** [oklai/koala#673]
**Koala 2.2.0**

**Deleting Files off of my hard drive.**

I downloaded this program in hopes of learning Sass. However instead what I got was a program that has now deleted over half of my saved project files, programs and folders. This is not expressly stated on the website as an issue, and I had to come here to even see if any one else had this issue. Why does this happen and is there a fix? I will have to now restore my computer to a point BEFORE the install to even try to recover all of that lost data. I will not be using it further, as this experience has left a sour taste in my mouth. I hope this issue is resolved and addressed BEFORE developers download this program and have the same issue.

**Comment by zaygraveyard** [comment]
Does #638 explain what happened with you?

**Comment by StefJohns** [comment]
Almost exactly, except I created a folder for it. However, yes, I read that post before deciding to comment or not. I see that it may not be a bug, but it is still an issue I was unaware of prior to download.

**Comment by Ponchu** [comment]
Well, this deleted my entire secondary hard drive, honestly turn off your download link please, this ruined a lot, thanks.
