### ISSUE TITLE
Doesn't compile SCSS after update OSX to 10.13 (macOS High Sierra)

### ISSUE THREAD

**Issue by MonsterCritic** [oklai/koala#679]
Koala version: 2.2.0

Error message: 
/scss/styles.scss
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'sass' (>= 0) among 15 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/monstercritic/.gem/ruby/2.3.0:/Library/Ruby/Gems/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /Applications/Koala.app/Contents/Resources/app.nw/bin/sass:17:in `

**Comment by iamcubcs** [comment]
I have same problem, SCSS doesn't compile. Same error message, even in Adobe Dreamweaver.

**Comment by slipdem** [comment]
Same problem here.
High Sierra 10.13

**Comment by soxepo** [comment]
I have same problem.
High Sierra 10.13 / Koala 2.2.0

**Comment by iamcubcs** [comment]
Hello, this help me resolve the problem for me. 

1. Open Terminal
2. Install Homebrew:   ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
3. Do not close Terminal, open Mac Appstore and check Update, install all XCode Command Line Tools updates OR in my case, XCode Command Line Tools started install automaticly throught Terminal right after step 2.
4. Back to Terminal
5. Install Ruby:   brew install rbenv ruby-build
6. Install SASS gem:   sudo gem install -n /usr/local/bin sass

After this steps, everything works fine and I can compilate again with Koala or in Dreamweaver.

**Comment by deluigiluca** [comment]
I have the same problem ...
High Sierra 10.13
Command Line Tools for Xcode version 9.0 updated
Koala 2.2.0

Then I re-install:
 SASS 3.5.1 (Bleeding Edge) and Ruby 2.3.1p112

but still not working.

The error message now is:

`/bin/sh: sass: command not found`

Anyone have an idea how to solve this problem?

many thanks

**Comment by steelbridge-io** [comment]
I can compile using $ sass --watch /_directory_/  ...but Dreamweaver fails to execute compile
I wish I knew the commands DW was using so I don't do something wrong.

**Comment by seierup** [comment]
Hi.. Any news on this?

**Comment by juliancross** [comment]
sudo gem install -n /usr/local/bin sass 
it worked for me

**Comment by juliancross** [comment]
sudo gem install -n /usr/local/bin sass
it worked for me with visual studio code

**Comment by juliancross** [comment]
sudo gem install -n /usr/local/bin sass
it worked for me with visual studio code but if you want to rework an old project css in sass it erases the css so make a backup

**Comment by delowar64** [comment]
Check this:

https://stackoverflow.com/questions/46511870/doesnt-compile-scss-after-update-osx-to-10-13-macos-high-sierra

**Comment by slipdem** [comment]
@delowar64 I try this earlier - no result in my case

**Comment by delowar64** [comment]
did you update command line tools?
https://goo.gl/t3DwrB
if not, update this & try again.

**Comment by slipdem** [comment]
@delowar64 Yes, command line tools updated.
 
Ps.
Back to Gulp in small projects))

**Comment by deluigiluca** [comment]
@slipdem I have the same problem, I'm using Scout for now, but I hope Koala will work again soon ...

**Comment by deluigiluca** [comment]
CodeKit works too... but I would prefer Koala instead.
Could be a problem of files permissions?

**Comment by aitala** [comment]
Tried the fixes with no luck...

**Comment by therealmikep** [comment]
Just ran into this and got it fixed.

I was seeing **"[Errno 2] No such File or Directory"** when trying to build .scss in both SublimeText 2 and 3. It's worked with other OS updates but after updating to High Sierra looks like I had to reinstall SASS from terminal. 

Here's a quick post:
https://michaelpilsner.com/sass-wont-build-sublime-text-mac-high-sierra-errno-2-no-file-directory/

**Comment by thecopt** [comment]
I have a same problem. 
I follow @iamcubcs step but not work.

**Comment by deluigiluca** [comment]
same here ... I've tried everything, but no solution yet

**Comment by aitala** [comment]
Ok, I found that installing the command line tools for Xcode / High Sierra seemed to fix the issue.

**Comment by thecopt** [comment]
This way is work. [https://github.com/oklai/koala/issues/679#issuecomment-332510652](url)
but step 3 if you can't fine update at check Update on  Mac Appstore. You try open xcode app for install component update.

**Comment by sippapeg** [comment]
same here,
I've followed @iamcubcs solution, it's work for me.

thanks,

**Comment by cobymotion** [comment]
I had same problem and the solution of @iamcubcs it's worked for me, but before i had to update Xcode. 

Thanks a lot !

**Comment by deluigiluca** [comment]
to me still not working ... I follow @iamcubcs instructions but I had the message error saying:
`/bin/sh: sass: command not found`

Now I've tried to un-install and re-install many times sass, node-sass, ruby update etc.etc.(maybe too much) and the error message in koala now is:
```
/Applications/XAMPP/xamppfiles/htdocs/style.scss
/Library/Ruby/Site/2.3.0/rubygems/dependency.rb:308:in to_specs: Could not find sass (>= 0) among 19 total gem(s) (Gem::MissingSpecError)
Checked in GEM_PATH=/Users/myname/.gem/ruby/2.3.0:/Library/Ruby/Gems/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0, execute gem env for more information
	from /Library/Ruby/Site/2.3.0/rubygems/dependency.rb:320:in to_spec'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in gem'
	from /Applications/Koala.app/Contents/Resources/app.nw/bin/sass:17:in
```
Does anyone understand where I'm doing wrong? 
Many thanks

**Comment by thecopt** [comment]
@deluigiluca try  sudo gem install compass

**Comment by ierika** [comment]
@iamcubcs Works great! just need to install some Xcode stuff and `gcc`. After that, `sudo gem install sass` worked fine.

**Comment by deluigiluca** [comment]
@thecopt Thank you...but still not working

**Comment by thecopt** [comment]
@deluigiluca try run sass -v

**Comment by deluigiluca** [comment]
@thecopt it give me: 

> Sass 3.5.2 (Bleeding Edge)

**Comment by thecopt** [comment]
@deluigiluca please run compass -v

**Comment by deluigiluca** [comment]
@thecopt 
> Compass 1.0.3 (Polaris)
> Copyright (c) 2008-2017 Chris Eppstein
> Released under the MIT License.
> Compass is charityware.
> Please make a tax deductable donation for a worthy cause: http://umdf.org/compass

**Comment by thecopt** [comment]
@deluigiluca update xcode ?

**Comment by deluigiluca** [comment]
@thecopt I updated on 27 of September, I have the version 9.0, Command Line Tools (macOS High Sierra version 10.13) ... thanks for trying me help

**Comment by ierika** [comment]
@deluigiluca try `xcode-select --install` first.

**Comment by deluigiluca** [comment]
@ierika (thank you) 
it says:

> xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by ssandovalCSD** [comment]
I am having the same issue and it is driving me nuts. I am on the latest version of High Sierra. Any issues with this? I am running Koala with Adobe Brackets app.

**Comment by deluigiluca** [comment]
@ssandovalCSD me too. I guess I must uninstall and reinstall everything, but I don't have time to do it now. By the way, I'm running Koala with many programs, but the error message not belongs if I'm running it with Brackets, Sublime text, Visual Studio Code, Dreamweaver or others ...

**Comment by ssandovalCSD** [comment]
Just followed iamcubus and it worked.

**Comment by elalienx** [comment]
Hi thanks to @iamcubcs its steps solve my issue on an updated OS from Sierra to High Sierra. Next time I will do a clean install.

**Comment by grafxflow** [comment]
I have followed @iamcubcs instructions but I am still getting the same error message. Plus it only started happening after installing High Sierra 10.13.

**Comment by masomi79** [comment]
had seme problem after installing High Sierra 10.13.

this worked for me:
  sudo gem install -n /usr/local/bin sass
  sudo gem install -n /usr/local/bin compass

**Comment by grafxflow** [comment]
Just tried @masomi79 solution but I am still having the same issue :(

**Comment by deluigiluca** [comment]
me too ...

**Comment by christian-fries** [comment]
I had the same problem...

This worked for me:
Open Xcode (if not installed, install it from the App Store). It asks you to install additional required components. Do it. Then follow @masomi79 s solution and you'll be happy again 😃

**Comment by robincher** [comment]
I ran these commands after updating to High-Sierra ,and now its working fine. Thanks @masomi79 for specifying that too.

```
xcode-select --install
  sudo gem install -n /usr/local/bin sass
  sudo gem install -n /usr/local/bin compas
```

**Comment by miqalarcia** [comment]
Hi everybody,

I have the same problem. I've tried everything commented here. Nothing worked. The most strange for me is that Codekit is working and, thanks god, this saved my life. It's a pitty because I love Koala. I hope it will solve soon.

**Comment by arielpont** [comment]
@iamcubcs steps works on my case :)
Thanks a lot!! Im usign Koala again woooooh!!!

**Comment by zaygraveyard** [comment]
Sorry for the delay.
I think I fixed the problem
I'll cut a new release tonight

**Comment by zaygraveyard** [comment]
Can anyone verify that this is fixed in [v2.3.0](https://github.com/oklai/koala/releases/tag/v2.3.0)?

**Comment by PAULUSfranCIRCUS** [comment]
@zaygraveyard I can verify that it works. Installing v2.3.0 fixed the ruby dependency error

**Comment by zaygraveyard** [comment]
Fantastic, thank you @PAULUSfranCIRCUS

**Comment by ykbryan** [comment]
I ran this to fix mine:
`sudo gem install cocoapods`

**Comment by TMWagner** [comment]
This repaired my broken Compass:

See [https://stackoverflow.com/questions/46511870/doesnt-compile-scss-after-update-osx-to-10-13-macos-high-sierra](url)

**Comment by zaygraveyard** [comment]
Koala v2.3.0 should work out-of-the-box, without having to run anything (unless you are using a custom command in the settings)
If it's not the case please let me know.

**Comment by binjuhor** [comment]
I follow @deluigiluca and it worked with me.

**Comment by mclck** [comment]
update Koala to 2.3.0

**Comment by harrycb** [comment]
I tried the method advised by @ iamcubcs  and it fixed the issues updating to 10.13.2 and compiling using SASS with Grunt.

**Comment by zaygraveyard** [comment]
@harrycb if you are use using Grunt then you probably not using Koala.
This a thread for Koala.

Unless you updated Koala and now experiencing this problem, **please don't comment on this issue**

**Comment by shuvaramva** [comment]
Thanks @iamcubcs

**Comment by CarloAntonio** [comment]
this worked for me:
1. Open Xcode (if not installed, install it from the App Store). It asks you to install additional required components. Do it.
2. xcode-select --install
3.   sudo gem install -n /usr/local/bin sass
  4. sudo gem install -n /usr/local/bin compass

Credit: @masomi79, @christian-fries, and @robincher 
They pointed it out, I just combined the steps together.
