### ISSUE TITLE
Windows Installer - incomplete path removes other files

### ISSUE THREAD

**Issue by joalsdnf** [oklai/koala#680]
**Koala 2.2.0 Windows Installer (Windows 10)**

If destination folder is changed from deafault and it's incomplete ( without adding "/Koala" directory in path) installer **deletes** other files in directory **without any warning**

Example:

If i change path from _C:\Program Files\Koala_ to _D:\Programs_ (without adding _\Koala_ manualy) all my programs or other files will be removed from the directory.

**Comment by ZheniaFIT** [comment]
Can confirm, noticed this after my files got removed

**Comment by zaygraveyard** [comment]
Duplicate of #638
