### ISSUE TITLE
File path cyrilic symbols issue

### ISSUE THREAD

**Issue by sergnewman** [oklai/koala#684]
**Koala version**
2.2.0
**Bug report or feature request?**
D:\Водка\css\other\myfeatures.scss
ArgumentError: invalid byte sequence in UTF-8
  Use --trace for backtrace.

It's look like the trouble caused within cyrillic symbols in folder's name
Koala is greate, but this think make me crazy...

**Comment by zaygraveyard** [comment]
Merge into #648
