### ISSUE TITLE
Update Sass to newest version (3.5.x)

### ISSUE THREAD

**Issue by antruongnguyen** [oklai/koala#697]
**Koala version**
v2.2.0

**Feature request**
Regarding to [Bootstrap v4 issue](https://github.com/twbs/bootstrap/pull/24354), please update Sass to newest version.

Many thanks!

**Comment by zaygraveyard** [comment]
Fixed in [v2.3.0](https://github.com/oklai/koala/releases/tag/v2.3.0)
