### ISSUE TITLE
Koala don't compile sass with Mac High Sierra

### ISSUE THREAD

**Issue by amapizen** [oklai/koala#699]
**Koala version**

**Bug report or feature request?**

**Comment by paulcheney** [comment]
Same problem, seems to be a problem related to Ruby Framework.
Any plans to correct this problem?

**Comment by amapizen** [comment]
I use Gulp or Grunt to compile in High Sierra, that's why i don't recommend to use graphic compilers.

**Comment by paulcheney** [comment]
I found "Scout-App" that works great in High Sierra until Koala get updates.

**Comment by amapizen** [comment]
Yeah but use Graphic Compilers like GhostLab CodeKit etc doesn't help, future is to use task managers ej Gulp. Scout is for newbies

**Comment by zaygraveyard** [comment]
Duplicate of #679
