### ISSUE TITLE
Safe to install Koala?

### ISSUE THREAD

**Issue by Klipper** [oklai/koala#704]
I try to install latest version of Koala (2.3.0) on my Win 10 laptop. During installation I get an alert that the directory C:\Program Files (x86)\Koala\  already exist, and that the installer will delete all existing files and folders in that directory before installing Koala. 
The very weird thing is that there is no directory 'Koala' on my system at all. When I change name of directory from 'Koala' to i.e. 'KoalaCompiler' I again get the same alert. So I don' t dare to go on, because I'm not sure files and folders will deleted like in issue #638. Please tell me what's going on? Is it safe to go on with this installer?
![image](https://user-images.githubusercontent.com/3924467/33140216-a1501cde-cfaf-11e7-9b2f-a8ebba5f0f8a.png)

**Comment by zaygraveyard** [comment]
That's very weird indeed 😕.
Sorry about that, I could have sworn I tested this case.
Normally it's safe to install (it's just the warning that is misplaced), but I'll test it tonight (in ~3 hours) and let you know.

**Comment by zaygraveyard** [comment]
I tried it and the same thing happened
And I can confirm it’s safe to install 
I’ll fix it ASAP

**Comment by Klipper** [comment]
Hi thanks for fast reaction. It's good to hear that this is only a weird bug. I'll try to install Koala this evening bypassing  the weird alert. Hope you can fix this issue as soon as possible. Please update the minor versionnumber of the installer too.

**Comment by zaygraveyard** [comment]
Fixed and updated the installer (and updated it's file version)

**Comment by Klipper** [comment]
Thanks again for fast actions.  Maybe one more tip. Update the text of your downloadbutton on http://koala-app.com/ too. So your visitor knows he/she download the latest version and not the one from 2017-05-02

**Comment by zaygraveyard** [comment]
Thank you for reporting this bug.
Nice catch 😄, fixed.
