### ISSUE TITLE
BUG: Koala replaces/changes a css statement after compile

### ISSUE THREAD

**Issue by EmmanuelGa** [oklai/koala#710]
**v2.3.0**

**Bug report**

Hi, in our css files we use a css statement with the following selector:

```
select:not(*:root) {
    /* some code */
}
```

After compileing the code Koala replaces/changes the selector to 

```
select:not(:root) {
    /* some code */
}
```
so we have to add the `*` manually. Is there any way to fix that?

best regards
Emmanuel

**Comment by zaygraveyard** [comment]
`*:root` and `:root` are equivalent so you actually need to add the `*`
And BTW it's not Koala that's making this change but the compiler LESS, SASS or clean-css (whichever you are using).
