### ISSUE TITLE
App show black screen Issue

### ISSUE THREAD

**Issue by pcasanellasp** [oklai/koala#712]
**Koala version**
Koala 2.3.0 Windows

**Bug report or feature request?**
Frame shows a black screen. App work correctly behind but i don't see anything

![image](https://user-images.githubusercontent.com/8070797/33715876-62d7f340-db54-11e7-98c3-f8c761d42d3f.png)

**Comment by zaygraveyard** [comment]
Which version of windows are you using?

**Comment by pcasanellasp** [comment]
Windows 10 Home 64 bits, all update.

**Comment by zaygraveyard** [comment]
Did you try quitting Koala completely and relaunching it? Or better yet restarting your computer?
I honestly have no idea, it's the first time I see such a case 😓

**Comment by pcasanellasp** [comment]
Solved! The problem was a Nvidia configuration on Nvidia Control Panel.

**Comment by zaygraveyard** [comment]
Great 👍 
Thanks for sharing the solution 😄 
Closing since it's resolved.

**Comment by herrrilke** [comment]
hey pcasanellasp,
please could you provide any further information as i am having the same issues and not shure which Nvidia configuration parameter to change.
thanks and best regards!
