### ISSUE TITLE
 downloading KoalaSetup.exe

### ISSUE THREAD

**Issue by KatrinBelova** [oklai/koala#727]
**Koala version**

**Bug report or feature request?**

I was downloading KoalaSetup.exe from http://koala-app.com/, but process was stoped on the last minute. It repited 5 times already

**Comment by zaygraveyard** [comment]
What is your download speed?

**Comment by KatrinBelova** [comment]
Thank you! :)
It's downloaded.
17 Янв 2018 г. 15:05 пользователь "Ziad El Khoury Hanna" <
notifications@github.com> написал:

**Comment by zaygraveyard** [comment]
Fantastic 😄
