### ISSUE TITLE
Uglify JS removes quotes from field names

### ISSUE THREAD

**Issue by Laza** [oklai/koala#733]
**Koala version: 2.3.0**

**Bug report or feature request?: Not sure**

Recently Koala removes quote marks around JS field names:
`a = { 'class': 'foo' }; -> a={class:"foo"};`

If you try the same on http://refresh-sf.com/ you get: 
`a={"class":"foo"};`

Previously Koala did not do this either.

Unfortunately this makes nearly impossible creating jQuery objects with 'class' attributes, as IE11 and below chokes on the class attribute (being a reserved word) and throws itself back to "Quirks mode", which behaves just like an IE6 - which we don't support now.

I could not find any setting that could resolve this issue. Could you please help?

**Comment by zaygraveyard** [comment]
Koala v2.3.0 uses UglifyJS 3.1.9
And UglifyJS 3 by default doesn't care about IE8, but you can enable it using the `ie8` flags.
You can try it out [here](https://skalman.github.io/UglifyJS-online/) (You only need to set `output.ie8` to `true`).

In Koala setting custom options for Uglify is not currently possible, sorry (see #703)

**Comment by Laza** [comment]
Okay, but this affects IE9, 10 and 11 too, which equals to some 5-10% of the visitors. This is not acceptable for a web designer.

**Comment by zaygraveyard** [comment]
I understand and I'm not saying you should drop support for them.
I was just explaining the situation.
I hope I can find time to add support for specifying custom options soon.
Unless you or someone else can submit a PR, in which case I'd be happy to review and merge it 😄
