### ISSUE TITLE
crashed editor and lost files

### ISSUE THREAD

**Issue by Annuther** [oklai/koala#738]
**Koala version** 2.2.0
Windows 8.1
Notepad++ v7.5.4 32-Bit

Bug report?

Using Koala in Notepad++ latest version as my editor - while a less file was compiling (green popup showing progress in bottom right-hand corner) - Koala crashed and made notepad++ crash causing me to lose the entire contents of the less file and the css file it was compiling to!!

When i opened the Koala interface (which is running minimised in the task bar) there was a popup prompting me to upgrade to the latest version. Ok, but this update/version checking should not interfere with the app currently operating on a file.

**Comment by zaygraveyard** [comment]
Only the latest version of Koala is supported, so you should update to it.
And if this problem happens again please reopen this issue.
