### ISSUE TITLE
Koala dies on start up

### ISSUE THREAD

**Issue by brettr91** [oklai/koala#740]
**Koala version V 2.3.0**

![koala](https://user-images.githubusercontent.com/3278557/37990673-d53b3fc4-31bb-11e8-97f6-c324886d3182.PNG)
![koala2](https://user-images.githubusercontent.com/3278557/37990674-d552f272-31bb-11e8-836a-6fa428773582.PNG)

**Bug report**

When I click to open Koala, I get the following pop ups - after clicking OK when koala opens it is a white box with nothing inside of it. It looks like having a null version number return from the server causes the application to die.

**Comment by zaygraveyard** [comment]
You can try deleting `%USERPROFILE%/.koala/settings.json`

**Comment by brettr91** [comment]
I know its a bit late - but thanks zaygraveyard that worked.

**Comment by zaygraveyard** [comment]
@brettr91 thank you

**Comment by iballi2017** [comment]
> You can try deleting `%USERPROFILE%/.koala/settings.json`

Thanks, It worked for me.
27 June, 2020

**Comment by codeparl** [comment]
Thanks, it worked for me!
