### ISSUE TITLE
计算表达式编译 bug

### ISSUE THREAD

**Issue by MrSoya** [oklai/koala#751]
v2.3.0

height: calc(100vh - $xxx);

$xxx不会被编译

**Comment by zaygraveyard** [comment]
What are you using, LESS or SCSS?

**Comment by MrSoya** [comment]
scss

**Comment by zaygraveyard** [comment]
This is actually an issue with the SCSS compiler, not Koala, see https://github.com/sass/sass/issues/818

**Comment by MrSoya** [comment]
thanks a lot
