### ISSUE TITLE
Will not open in Windows 10

### ISSUE THREAD

**Issue by francorona** [oklai/koala#753]
**Koala version**
2.3.0
**Bug report or feature request?**
Downloaded and installed on the computer - will not open.

**Comment by PHARMACIE1801** [comment]
I confirm that, does not open, no message at all, win 10 64bit

**Comment by francorona** [comment]
uninstalled

**Comment by danrichdan** [comment]
Similar issue. Koala opened for me, but not when I had PHP Storm running, and then later not at all. Uninstalling.
