### ISSUE TITLE
Less compiling

### ISSUE THREAD

**Issue by LoomyTrix** [oklai/koala#755]
Hello, new issue is found in koala v.2.3.0
        display: grid;
	grid-template-columns: repeat(12, [col] 1fr);
	grid-template-rows: repeat(2, [row] 1fr);

[col], [row] are perceived like error
I ask to add full support css grid

**Comment by zaygraveyard** [comment]
Koala is not a LESS compiler, it uses the [official LESS compiler](https://github.com/less/less.js)
Your example is not valid LESS, [try it online](http://lesscss.org/less-preview/#%7B%22less%22%3A%22a%20%7B%5Cn%20%20display%3A%20grid%3B%5Cn%20%20grid-template-columns%3A%20repeat(12%2C%20%5Bcol%5D%201fr)%3B%5Cn%20%20grid-template-rows%3A%20repeat(2%2C%20%5Brow%5D%201fr)%3B%5Cn%7D%22%7D)
