### ISSUE TITLE
Koala with “sass-json-vars”: CLI works, but GUI gets “Cannot load such file sass-json-vars”

### ISSUE THREAD

**Issue by cfuj** [oklai/koala#765]
**Koala version** 2.30

**Bug report or feature request?** Koala with “sass-json-vars”: CLI works, but GUI gets “Cannot load such file sass-json-vars”

I have `C:\Program Files (x86)\Koala\ruby\lib\ruby\bin` added to the `PATH environment variable`.

When I install this gem with `gem install sass-json-vars`, it's installed to `C:\Program Files (x86)\Koala\ruby\lib\ruby\gems\2.0.0\gems`

When I run the command `sass core.scss core.css -r sass-json-vars --trace`, it works fine.

But if I open `koala-config.json` in my project-root and add `"customOptions": ["-r sass-json-vars"],`, each attempt by the GUI, or the GUI's 'watcher', to compile gives me the error **`"Cannot load such file -- sass-json-vars"`**.

If I remove the command, and the attempt to import json, the GUI works fine.

**Comment by zaygraveyard** [comment]
Can you try: `"requireLibs": ["sass-json-vars"],` ?

**Comment by cfuj** [comment]
Thanks for the prompt reply. It gives me the same error.

Here's my `koala-config.json`

```
// Sass project settings, you can edit it and set custom settings.
{
	// The mappings of source directory and output directory
	"mappings": [
		{
		  "src": "-src/assets/css",
		  "dest": "httpdocs/assets/css"
		}
	],

	// Add the ignore rules that Koala will not search them.
	// e.g. ["*.json", "*.txt", "test", "path/libs"]
	"ignores": ["*.css", "*.json"],

	// Compile options of Sass.
	"options": {

		// Output style. Can be nested (default), compact, compressed, or expanded.
		"outputStyle": "nested",

		// Emit comments in the generated CSS indicating the corresponding source line.
		"lineComments": false,

		// Emit extra information in the generated CSS that can be used by the FireSass Firebug plugin.
		"debugInfo": false,

		// Create sourcemap files next to the generated CSS files
		"sourceMap": false,

		// Use Unix-style newlines in written files.
		"unixNewlines": false,

        // auto add vendor prefixes to rules
        "autoprefix": false,
        "autoprefixConfig" : "> 1%, last 2 versions, Firefox ESR, Opera 12.1"
	},

	// Other compile options, use the full name of options.
	// e.g, ["--scss", ... ,"--no-cache"].
	// Run the command 'sass -h' to see more options.
	"customOptions": [], // ["-r sass-json-vars"],

	// An array of filesystem paths or importers which should be searched for Sass templates imported with the @import directive.
	"includePaths": [],

	// A array of ruby libraries, require them before running Sass.
	"requireLibs": ["sass-json-vars"]
}
```
I'm not sure that it matters, but I tried also tried an external ruby installation, to the same results.

**Comment by zaygraveyard** [comment]
Can you try installing `sass-json-vars` with `gem install -i "C:\Program Files (x86)\Koala\rubygems" sass-json-vars`?

**Comment by cfuj** [comment]
It works! Thank you!

**Comment by zaygraveyard** [comment]
Fantastic 😄
