### ISSUE TITLE
How to use first line comments?

### ISSUE THREAD

**Issue by antikmozib** [oklai/koala#789]
Is there any documentation on using the line comments?

Like this:

```
[file1.scss]
// main: mainfile.scss

[mainfile.scss]
// out: style.min.css
@import "file1.scss";
```

So saving file1.scss creates/updates only style.min.css.

**Comment by zaygraveyard** [comment]
That's the first time I see those, does it work?

**Comment by antikmozib** [comment]
[
![untitled](https://user-images.githubusercontent.com/45801225/50762221-75bf4180-12c0-11e9-94a1-c826cb5775af.png)
](url)

That's what I'm trying to understand, especially after noticing the option on the window.

**Comment by zaygraveyard** [comment]
The "line comments" option is translated to "--line-comments" when passed to the `sass` compiler, which enables the [line numbers option](https://sass-lang.com/documentation/file.SASS_REFERENCE.html#line_numbers-option).
> When set to true, causes the line number and file where a selector is defined to be emitted into the compiled CSS as a comment. Useful for debugging, especially when using imports and mixins. This option may also be called :line_comments. Automatically disabled when using the :compressed output style or the :debug_info/:trace_selectors options.

**Comment by antikmozib** [comment]
OK thanks for the clarification.
