### ISSUE TITLE
Don’t open the software 

### ISSUE THREAD

**Issue by Larinmj** [oklai/koala#792]
**Koala version**

**Bug report or feature request?**

By minimizing software, I can't open it anymore

**Comment by zaygraveyard** [comment]
It's in the tray icons section of your taskbar

**Comment by Larinmj** [comment]
What do you mean?
Cus, the icon is fixed in my taskbar, but when I had clicked, dont open.

**Comment by zaygraveyard** [comment]
I mean like #360 
Is this your case?

**Comment by zaygraveyard** [comment]
Any updates?
