### ISSUE TITLE
Error: wrong number of arguments (4 for 3) for rgb

### ISSUE THREAD

**Issue by deeve007** [oklai/koala#804]
**Koala version**
2.3.0

**Bug report or feature request?**
When trying to save file, this line gives the above error message:
background-color: rgb(17, 159, 208, .05);

That looks correctly formatted to me, so is this a bug or do I need to format this differently than in standard CSS?

**Comment by ziadkh0** [comment]
This is not a bug
`rgb()` takes 3 arguments
`rgba()` takes 4 (the last one being alpha)
So you probably want to use `rgba()` instead of `rgb()`

**Comment by deeve007** [comment]
My apologies, I had googled the bejesus out of this with nothing coming up, and then just before you commented I found something. 20 years I've been CSSing using rgb with alpha declaration fine, and didn't even know there was an rgba!!!!! Thanks for your patience with dumbasses like me.
