### ISSUE TITLE
Compile Error: Must Compile Individual Stylesheets From Project Directory

### ISSUE THREAD

**Issue by ezmiller** [oklai/koala#87]
HI,
I'm getting another error using koala 1.4.1 and Ubuntu 13.04. When I save my sass file, I'm giving the following error message:

> You must compile individual stylesheets from the project directory. 

I'm not sure what this is supposed to mean...

**Comment by sweakley23** [comment]
This worked for me after searching all over the web
Configuration: windows 7, ruby 2.2, compass 1.01 (installed through ruby), Koala
Koala Settings:
using system compiler Compass 
C:\Ruby22-x64\bin\compass
using system compiler Ruby 
C:\Ruby22-x64\bin\sass

Right click on root folder in Koala and select "Project settings > New Settings > For Compass"
Then edit config.rb it creates at website root as below

http_path = "/"
css_dir = "/css" //or directory to your css relative to the config.rb created
sass_dir = "/css" //or directory to your Scss relative to the config.rb created
images_dir = "images"
javascripts_dir = "/js"  //or directory to your javascript scripts relative to the config.rb created

then the mappings of my koala-config.json file is changed to below
    "mappings": [
        // {
        // 	"src": "C:\\Ampps\\www\\practice\\css",  // double backslashes to escape them
        // 	"dest": "C:\\Ampps\www\\practice\\css"   // double backslashes to escape them
        // }
    ],
