### ISSUE TITLE
Auto compile for javascript

### ISSUE THREAD

**Issue by d0ragon** [oklai/koala#98]
Right now only LESS and coffeeScript files have the option to be auto compiled. Why don't the ordinary javascript files have this option? Any chance this gets added?

**Comment by richjenks** [comment]
Is it possible to enable js auto compile in `koala-config.json`? While I agree in most cases it's better to not watch during development, it would be beneficial to at least be able to make it enabled by default at the project level.

**Comment by julmot** [comment]
That is a core functionality!


-------- Ursprüngliche Nachricht --------
Von: Rich Jenks <notifications@github.com> 
Datum: 27.01.2015  11:48  (GMT+01:00) 
An: oklai/koala <koala@noreply.github.com> 
Betreff: Re: [koala] Auto compile for javascript (#98) 

Is it possible to enable js auto compile in koala-config.json? While I agree in most cases it's better to not watch during development, it would be beneficial to at least be able to make it enabled by default at the project level.

**Comment by richjenks** [comment]
Not sure what you're saying — I mean that it's in the interface, but it would be advantageous to be able to store (and version!) all settings in the config file.

**Comment by julmot** [comment]
I've misunderstood you. Yes @oklai that would be great
